### ISSUE TITLE
Failed assertion (!empty()) in detectMultiScale when running example

### ISSUE THREAD

**Issue by andybons** [hybridgroup/gocv#108]
Environment:

```sh
gocv version: 0.9.0
opencv lib version: 3.4.0

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.3
BuildVersion:   17D102
```

When running the example from https://gocv.io/writing-code/face-detect/ (the https://gocv.io/writing-code/hello-video/ ran perfectly) I see my camera’s green light go on, then the program crashes:

```
start reading camera device: 0
OpenCV Error: Assertion failed (!empty()) in detectMultiScale, file /tmp/opencv-20180113-80339-d8g5mw/opencv-3.4.0/modules/objdetect/src/cascadedetect.cpp, line 1698
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20180113-80339-d8g5mw/opencv-3.4.0/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215) !empty() in function detectMultiScale

SIGABRT: abort
PC=0x7fff599bbe3e m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x409a530, 0xc420059dd8, 0xc420000180)
        /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420059da8 sp=0xc420059d70 pc=0x40047f4
gocv.io/x/gocv._Cfunc_CascadeClassifier_DetectMultiScale(0xa404c90, 0xa4500a0, 0x0, 0x0)
        _cgo_gotypes.go:674 +0x4d fp=0xc420059dd8 sp=0xc420059da8 pc=0x409604d
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale.func1(0xa404c90, 0xa4500a0, 0x0, 0x0)
        /Users/andybons/gocode/src/gocv.io/x/gocv/objdetect.go:53 +0x94 fp=0xc420059e20 sp=0xc420059dd8 pc=0x4097a54
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale(0xc420059f28, 0xa4500a0, 0x0, 0x0, 0x0)
        /Users/andybons/gocode/src/gocv.io/x/gocv/objdetect.go:53 +0x56 fp=0xc420059e98 sp=0xc420059e20 pc=0x4097206
main.main()
        /<snip>/main.go:49 +0x23e fp=0xc420059f88 sp=0xc420059e98 pc=0x409819e
runtime.main()
        /usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420059fe0 sp=0xc420059f88 pc=0x402b522
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420059fe8 sp=0xc420059fe0 pc=0x40520f1

rax    0x0
rbx    0x7fff928c2340
rcx    0x7ffeefbfdcb8
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfdcf0
rsp    0x7ffeefbfdcb8
r8     0x7ffeefbfdb80
r9     0xa5489c0
r10    0x0
r11    0x206
r12    0x307
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff599bbe3e
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by berak** [comment]
`Assertion failed (!empty())`

your cascade file did not load. check the path to it again, and add some error handling like:

```
	if !classifier.Load(xmlFile) {
		fmt.Printf("Error reading cascade file: %v\n", xmlFile)
		return
	}

```

**Comment by deadprogram** [comment]
Hi @andybons the `dev` branch already has merged the improved version with error handling that @berak contributed, which will be part of the next release:

https://github.com/hybridgroup/gocv/blob/dev/cmd/facedetect/main.go#L59

**Comment by berak** [comment]
> I’m assuming that it will also update the example code on the website?

not so, unfortunately. 

(question here: which is the appropriate branch for https://github.com/hybridgroup/gocv-site ?)
