### ISSUE TITLE
Fail to write an image to gocv.VideoWriter

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#190]
So, here's what i do. I have a function that get's an image from store:
```go
func saveImageFromURL(imgURL string) (gocv.Mat, error) {
	dummy := gocv.Mat{}
	resp, err := http.Get(imgURL)
	if err != nil {
		return dummy, err
	}

	content, _ := ioutil.ReadAll(resp.Body)
	if resp.StatusCode > 202 {
		return dummy, errors.New(string(content))
	}
	defer resp.Body.Close()

	m := gocv.IMDecode(content, gocv.IMReadColor)
	if m.Empty() {
		return dummy, fmt.Errorf("invalid image content from URL: `%s`", imgURL)
	}
	return m, nil
}
```
i'm calling one several times to get a list of images (`[]gocv.Mat`)
later i use the next function:
```go
func writeImagesToVideo(images []gocv.Mat, tempVideoFileName string, w, d int) error {
	writer, err := gocv.VideoWriterFile(
		tempVideoFileName, "MP4V", float64(len(images)), w, h)
	if err != nil {
		return fmt.Errorf("error opening video writer device: "+
			"%v, original erorr: %v\n", tempVideoFileName, err)
	}
	defer writer.Close()

	for _, img := range images {
		err = writer.Write(img)
		if err != nil {
			return err
		}
	}
	return nil
}
```
so, all images in store are valid, each `gocv.Mat` for image(s) is valid and not empty, however, i get the following error:
```
018/05/11 12:51:12 temp video file created: 45.mp4
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x7f84a004d3de]

runtime stack:
runtime.throw(0x6e2f93, 0x2a)
        /usr/local/go/src/runtime/panic.go:619 +0x81
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x633a60, 0xc420071958, 0xc420208550)
        /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420071928 sp=0xc4200718f0 pc=0x4219d4
function/vendor/gocv.io/x/gocv._Cfunc_VideoWriter_Write(0x7f8490f21fc0, 0x0)
        _cgo_gotypes.go:3616 +0x41 fp=0xc420071958 sp=0xc420071928 pc=0x62f171
function/vendor/gocv.io/x/gocv.(*VideoWriter).Write.func1(0x7f8490f21fc0, 0x0)
        /go/src/function/vendor/gocv.io/x/gocv/videoio.go:274 +0x8f fp=0xc420071990 sp=0xc420071958 pc=0x62fa9f
function/vendor/gocv.io/x/gocv.(*VideoWriter).Write(0xc420432560, 0x0, 0x0, 0x0)
        /go/src/function/vendor/gocv.io/x/gocv/videoio.go:274 +0x7f fp=0xc4200719b8 sp=0xc420071990 pc=0x62f6ff

```
the error is not verbose at all, unfortunately.

**Comment by deadprogram** [comment]
This code has now been released as part of v0.12.0 so now closing. Thanks again!
