### ISSUE TITLE
unexpected error !

### ISSUE THREAD

**Issue by Mddct** [hybridgroup/gocv#262]
When i go run this code segment, I got error :
package main
```go
import (
	"gocv.io/x/gocv"
)

func main() {
	img := gocv.IMRead("1.jpeg", gocv.IMReadColor)
	defer img.Close()

	window := gocv.NewWindow("hello")
	defer window.Close()

	for i := 0; i < img.Rows(); i++ {
		for j := 0; j < img.Cols(); j++ {
			for k := 0; k < img.Channels(); k++ {
				c := img.GetUCharAt3(i, j, k)
				c = uint8(float32(c) * 0.01 * 200)
				img.SetUCharAt3(i, j, k, c)
			}
		}
	}

	_ = window
}
``` 

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x135b4868 pc=0x4089256]

runtime stack:
runtime.throw(0x40cb122, 0x2a)
	/Users/mddct/Program/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/Users/mddct/Program/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4084f50, 0xc420055ec8, 0x40caeb5)
	/Users/mddct/Program/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420055e80 sp=0xc420055e48 pc=0x4005894
gocv.io/x/gocv._Cfunc_Mat_GetUChar3(0xa901f10, 0x0, 0x1, 0x0)
	_cgo_gotypes.go:2655 +0x4a fp=0xc420055ec8 sp=0xc420055e80 pc=0x408310a
gocv.io/x/gocv.(*Mat).GetUCharAt3.func1(0xa901f10, 0x0, 0x1, 0x5500000003)
	/Users/mddct/Program/go_packages/src/gocv.io/x/gocv/core.go:361 +0x6e fp=0xc420055f00 sp=0xc420055ec8 pc=0x4083d6e
gocv.io/x/gocv.(*Mat).GetUCharAt3(0xc420055f70, 0x0, 0x0, 0x1, 0x55)
	/Users/mddct/Program/go_packages/src/gocv.io/x/gocv/core.go:361 +0x49 fp=0xc420055f30 sp=0xc420055f00 pc=0x40837d9
main.main()
	/Users/mddct/learn/opencv/tracker2.go:17 +0xde fp=0xc420055f88 sp=0xc420055f30 pc=0x408423e
runtime.main()
	/Users/mddct/Program/go/src/runtime/proc.go:198 +0x212 fp=0xc420055fe0 sp=0xc420055f88 pc=0x402c192
runtime.goexit()
	/Users/mddct/Program/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420055fe8 sp=0xc420055fe0 pc=0x4052401
exit status 2

**Comment by deadprogram** [comment]
Hello @Mddct you might want to ensure that `img.Empty() != true`.

The unit test for `Mat.GetUCharAt3()` can also be located here:

https://github.com/hybridgroup/gocv/blob/0d9b22a6450a7d81761a4b763f58fb99e962ab47/core_test.go#L311

Hope that helps!
