### ISSUE TITLE
windows: cmd/hello/main panics on ctrl+c

### ISSUE THREAD

**Issue by mxplusb** [hybridgroup/gocv#288]
## Description

`go run .\cmd\hello\main.go` -> `CTRL+C` causes a panic in runtime. I think it's OpenCV crashing which is causing the golang runtime to crash. 

## Steps to Reproduce

Run `go run .\cmd\hello\main.go`, wait for it to initialise, then hit `CTRL+C`.

```powershell
> go run .\cmd\hello\main.go
Exception 0xc000000d 0x0 0x0 0x7ffe9cfc8b00
PC=0x7ffe9cfc8b00

runtime: unknown pc 0x7ffe9cfc8b00
stack: frame={sp:0xdf1ec60, fp:0x0} stack=[0xdf17928,0xdf1fe30)
000000000df1eb60:  0000000000000002  0000000000000002
000000000df1eb70:  000020073e350000  000020073e357065
000000000df1eb80:  0000000000000000  0000000000000000
000000000df1eb90:  0000000000000001  0000000000276000
000000000df1eba0:  0000000000000002  0000000000000001
000000000df1ebb0:  000000000df1ecc0  00007ffe9cef59c5
000000000df1ebc0:  0000000000000048  0000000000000001
000000000df1ebd0:  0000000000000000  0000000000000000
000000000df1ebe0:  0000000000000000  0000000000000000
000000000df1ebf0:  0000000000000000  0000000000000000
000000000df1ec00:  0000000000000000  00007ffe9cf070a0
000000000df1ec10:  00007ffe00140012  00007ffe97ea6db8
000000000df1ec20:  000020073e357c35  000000000df1ef20
000000000df1ec30:  000000000088cfd0  000000000082b8f0
000000000df1ec40:  0000000000000000  00007ffe8eed7d40
000000000df1ec50:  0000000000868520  00007ffe9cfc8b00
000000000df1ec60: <0000000000000057  0000000000000001
000000000df1ec70:  0000000000868758  0000000000871d60
000000000df1ec80:  00000000c000000d  0000000000000000
000000000df1ec90:  00007ffe9cfc8b00  0000000000000000
000000000df1eca0:  0000000000000000  0000000000000000
000000000df1ecb0:  0000000000000000  0000000000000000
000000000df1ecc0:  0000000000000000  0000000000000000
000000000df1ecd0:  0000000000000000  0000000000000000
000000000df1ece0:  0000000000000000  0000000000000000
000000000df1ecf0:  0000000000000000  0000000000000000
000000000df1ed00:  0000000000000000  0000000000000000
000000000df1ed10:  0000000000000000  0000000000000000
000000000df1ed20:  000020073e357665  0000000000000000
000000000df1ed30:  0000000000871d60  00007ffe8eed4a09
000000000df1ed40:  0000000000871d60  000000000082b8f0
000000000df1ed50:  0000000000000000  0000000000000000
runtime: unknown pc 0x7ffe9cfc8b00
stack: frame={sp:0xdf1ec60, fp:0x0} stack=[0xdf17928,0xdf1fe30)
000000000df1eb60:  0000000000000002  0000000000000002
000000000df1eb70:  000020073e350000  000020073e357065
000000000df1eb80:  0000000000000000  0000000000000000
000000000df1eb90:  0000000000000001  0000000000276000
000000000df1eba0:  0000000000000002  0000000000000001
000000000df1ebb0:  000000000df1ecc0  00007ffe9cef59c5
000000000df1ebc0:  0000000000000048  0000000000000001
000000000df1ebd0:  0000000000000000  0000000000000000
000000000df1ebe0:  0000000000000000  0000000000000000
000000000df1ebf0:  0000000000000000  0000000000000000
000000000df1ec00:  0000000000000000  00007ffe9cf070a0
000000000df1ec10:  00007ffe00140012  00007ffe97ea6db8
000000000df1ec20:  000020073e357c35  000000000df1ef20
000000000df1ec30:  000000000088cfd0  000000000082b8f0
000000000df1ec40:  0000000000000000  00007ffe8eed7d40
000000000df1ec50:  0000000000868520  00007ffe9cfc8b00
000000000df1ec60: <0000000000000057  0000000000000001
000000000df1ec70:  0000000000868758  0000000000871d60
000000000df1ec80:  00000000c000000d  0000000000000000
000000000df1ec90:  00007ffe9cfc8b00  0000000000000000
000000000df1eca0:  0000000000000000  0000000000000000
000000000df1ecb0:  0000000000000000  0000000000000000
000000000df1ecc0:  0000000000000000  0000000000000000
000000000df1ecd0:  0000000000000000  0000000000000000
000000000df1ece0:  0000000000000000  0000000000000000
000000000df1ecf0:  0000000000000000  0000000000000000
000000000df1ed00:  0000000000000000  0000000000000000
000000000df1ed10:  0000000000000000  0000000000000000
000000000df1ed20:  000020073e357665  0000000000000000
000000000df1ed30:  0000000000871d60  00007ffe8eed4a09
000000000df1ed40:  0000000000871d60  000000000082b8f0
000000000df1ed50:  0000000000000000  0000000000000000

goroutine 1 [syscall, locked to thread]:
gocv.io/x/gocv._Cfunc_Window_WaitKey(0x1, 0x0)
        _cgo_gotypes.go:4678 +0x54
gocv.io/x/gocv.(*Window).WaitKey(0xc0420543e0, 0x1, 0xffffffffffffff01)
        C:/Users/MikeLloyd/go/src/gocv.io/x/gocv/highgui.go:170 +0x31
main.main()
        C:/Users/MikeLloyd/go/src/gocv.io/x/gocv/cmd/hello/main.go:16 +0xc6
rax     0x0
rbx     0x1
rcx     0x0
rdi     0x871d60
rsi     0x868758
rbp     0x868520
rsp     0xdf1ec60
r8      0x0
r9      0x0
r10     0x0
r11     0x0
r12     0x7ffe8eed7d40
r13     0x0
r14     0x82b8f0
r15     0x88cfd0
rip     0x7ffe9cfc8b00
rflags  0x206
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

## Your Environment

* Operating System and version:

![image](https://user-images.githubusercontent.com/7537841/44940881-b1199480-ad51-11e8-92ff-9f6834ac9357.png)

* OpenCV version used: 

3.4.2

* How did you install OpenCV?

Followed the instructions on the gocv website.

* GoCV version used:

116580ad/master

* Go version:

```powershell
> go version
go version go1.10.2 windows/amd64
```

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

No.

**Comment by deadprogram** [comment]
That is not surprising given that example does not provide any error handling or exit logic. It is intended to show the minimum possible CV program. You probably would want to add your own SIGINT handler etc.

Hope that helps!

**Comment by mxplusb** [comment]
Oh okay, if that's expected, then it's fine. Thanks!
