### ISSUE TITLE
motion and save image failing

### ISSUE THREAD

**Issue by gesaleh** [hybridgroup/gocv#291]
I'm trying to combine motion detection to save image at each detection 
with a simple example based on motion detection and saveimage examples 

## Description
Once motion detected save an image (i have already image uploader but this is next step
The script use the motion example the threshold and minimal area will be adjusted to specific case

### Error :
```go run monitor.go 0 image_test
Start reading device: 0
Motion detected :  0
Motion detected :  395
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.2) /tmp/opencv-20180704-99354-1kt9ska/opencv-3.4.2/modules/imgcodecs/src/loadsave.cpp:684: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

SIGABRT: abort
PC=0x7fff5f477b66 m=0 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff5f477b66
stack: frame={sp:0x7ffeefbfde48, fp:0x0} stack=[0x7ffeefb80490,0x7ffeefbff910)
00007ffeefbfdd48:  00007fff97e19c90  0000000000000000 
00007ffeefbfdd58:  00007fff97e19c90  0000000000000307 
00007ffeefbfdd68:  00007fff97e19c88  00007ffeefbfdd90 
00007ffeefbfdd78:  00007ffeefbfddb0  00007fff97e19c90 
00007ffeefbfdd88:  00007ffeefbfdda0  0000000000000000 
00007ffeefbfdd98:  0000000032aaaba2  0000000000000000 
00007ffeefbfdda8:  00007ffeefbfdee0  0000000000000000 
00007ffeefbfddb8:  0000000032aaaba2  0000000000000000 
00007ffeefbfddc8:  0000000000000000  0000000000000000 
00007ffeefbfddd8:  0000000000000000  0000000000000000 
00007ffeefbfdde8:  0000000000000000  0000000000000000 
00007ffeefbfddf8:  0000000000000003  0000000000000000 
00007ffeefbfde08:  0000000000000000  0000000000000000 
00007ffeefbfde18:  0000000000000000  00007fff97e1a240 
00007ffeefbfde28:  00007fff97e19ca0  00007fff5f3b2366 
00007ffeefbfde38:  0000000000000000  00007ffeefbfde80 
00007ffeefbfde48: <00007fff5f642080  00007fff97e3b380 
00007ffeefbfde58:  00007ffeefbfde98  0000000000000008 
00007ffeefbfde68:  0000000000000030  00007fff5d2ee4d4 
00007ffeefbfde78:  00007fff97e1a9a0  00007ffeefbfdeb0 
00007ffeefbfde88:  00007fff5f3d31ae  0000000000000008 
00007ffeefbfde98:  00000000ffffffdf  ffffffff5d2ee4d4 
00007ffeefbfdea8:  00007ffeefbfdfb0  00007ffeefbfdfe0 
00007ffeefbfdeb8:  00007fff5d2cdf8f  0000003000000020 
00007ffeefbfdec8:  00007ffeefbfdff0  00007ffeefbfdf00 
00007ffeefbfded8:  0000ffff00001fa0  0000003000000020 
00007ffeefbfdee8:  00007ffeefbfdff0  00007ffeefbfdf00 
00007ffeefbfdef8:  000000000e8a6450  0000000008b32835 
00007ffeefbfdf08:  00007fff5d2ee55c  00007ffeefbfdff0 
00007ffeefbfdf18:  000000000ac0dac4  00007fff97730058 
00007ffeefbfdf28:  00007ffeefbfcf10  00007fff5e723ef0 
00007ffeefbfdf38:  00007fff5e70ddb2  0000000000000000 
runtime: unknown pc 0x7fff5f477b66
stack: frame={sp:0x7ffeefbfde48, fp:0x0} stack=[0x7ffeefb80490,0x7ffeefbff910)
00007ffeefbfdd48:  00007fff97e19c90  0000000000000000 
00007ffeefbfdd58:  00007fff97e19c90  0000000000000307 
00007ffeefbfdd68:  00007fff97e19c88  00007ffeefbfdd90 
00007ffeefbfdd78:  00007ffeefbfddb0  00007fff97e19c90 
00007ffeefbfdd88:  00007ffeefbfdda0  0000000000000000 
00007ffeefbfdd98:  0000000032aaaba2  0000000000000000 
00007ffeefbfdda8:  00007ffeefbfdee0  0000000000000000 
00007ffeefbfddb8:  0000000032aaaba2  0000000000000000 
00007ffeefbfddc8:  0000000000000000  0000000000000000 
00007ffeefbfddd8:  0000000000000000  0000000000000000 
00007ffeefbfdde8:  0000000000000000  0000000000000000 
00007ffeefbfddf8:  0000000000000003  0000000000000000 
00007ffeefbfde08:  0000000000000000  0000000000000000 
00007ffeefbfde18:  0000000000000000  00007fff97e1a240 
00007ffeefbfde28:  00007fff97e19ca0  00007fff5f3b2366 
00007ffeefbfde38:  0000000000000000  00007ffeefbfde80 
00007ffeefbfde48: <00007fff5f642080  00007fff97e3b380 
00007ffeefbfde58:  00007ffeefbfde98  0000000000000008 
00007ffeefbfde68:  0000000000000030  00007fff5d2ee4d4 
00007ffeefbfde78:  00007fff97e1a9a0  00007ffeefbfdeb0 
00007ffeefbfde88:  00007fff5f3d31ae  0000000000000008 
00007ffeefbfde98:  00000000ffffffdf  ffffffff5d2ee4d4 
00007ffeefbfdea8:  00007ffeefbfdfb0  00007ffeefbfdfe0 
00007ffeefbfdeb8:  00007fff5d2cdf8f  0000003000000020 
00007ffeefbfdec8:  00007ffeefbfdff0  00007ffeefbfdf00 
00007ffeefbfded8:  0000ffff00001fa0  0000003000000020 
00007ffeefbfdee8:  00007ffeefbfdff0  00007ffeefbfdf00 
00007ffeefbfdef8:  000000000e8a6450  0000000008b32835 
00007ffeefbfdf08:  00007fff5d2ee55c  00007ffeefbfdff0 
00007ffeefbfdf18:  000000000ac0dac4  00007fff97730058 
00007ffeefbfdf28:  00007ffeefbfcf10  00007fff5e723ef0 
00007ffeefbfdf38:  00007fff5e70ddb2  0000000000000000 

goroutine 1 [syscall]:
runtime.cgocall(0x409dd20, 0xc420067db0, 0xc420067db8)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420067d80 sp=0xc420067d48 pc=0x40055f4
gocv.io/x/gocv._Cfunc_Image_IMWrite(0xac10e10, 0xa90a6b0, 0x0)
	_cgo_gotypes.go:1651 +0x4a fp=0xc420067db0 sp=0xc420067d80 pc=0x4098c6a
gocv.io/x/gocv.IMWrite.func2(0xac10e10, 0xa90a6b0, 0xac10e10)
	/Users/gesaleh/go/src/gocv.io/x/gocv/imgcodecs.go:151 +0x60 fp=0xc420067de8 sp=0xc420067db0 pc=0x409a200
gocv.io/x/gocv.IMWrite(0x7ffeefbffb46, 0xa, 0xa90a6b0, 0x0)
	/Users/gesaleh/go/src/gocv.io/x/gocv/imgcodecs.go:151 +0x7c fp=0xc420067e18 sp=0xc420067de8 pc=0x40995ec
main.main()
	/Users/gesaleh/go/src/github.com/camgo/monitor.go:95 +0x577 fp=0xc420067f88 sp=0xc420067e18 pc=0x409b057
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420067fe0 sp=0xc420067f88 pc=0x402c322
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420067fe8 sp=0xc420067fe0 pc=0x4052e41

rax    0x0
rbx    0x7fff97e3b380
rcx    0x7ffeefbfde48
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfde80
rsp    0x7ffeefbfde48
r8     0x7ffeefbfdd10
r9     0xac247e0
r10    0x0
r11    0x206
r12    0x307
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff5f477b66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```
## Steps to Reproduce
The example code

```
package main

import (
        "fmt"
        "image"
        "os"
        "gocv.io/x/gocv"
)

const MinimumArea = 3000

func main() {
        if len(os.Args) < 2 {
                fmt.Println("How to run:\n\tmotion-detect [camera ID]")
                return
        }

        // parse args
        deviceID := os.Args[1]

        webcam, err := gocv.OpenVideoCapture(deviceID)
        if err != nil {
                fmt.Printf("Error opening video capture device: %v\n", deviceID)
                return
        }
        defer webcam.Close()

        img := gocv.NewMat()
        defer img.Close()

        imgDelta := gocv.NewMat()
        defer imgDelta.Close()

        imgThresh := gocv.NewMat()
        defer imgThresh.Close()

        mog2 := gocv.NewBackgroundSubtractorMOG2()
        defer mog2.Close()

        status := "Ready"

        fmt.Printf("Start reading device: %v\n", deviceID)
        for {
                if ok := webcam.Read(&img); !ok {
                        fmt.Printf("Device closed: %v\n", deviceID)
                        return
                }
                if img.Empty() {
                        continue
                }

                status = "Ready"
                //statusColor := color.RGBA{0, 255, 0, 0}

                // first phase of cleaning up image, obtain foreground only
                mog2.Apply(img, &imgDelta)

                // remaining cleanup of the image to use for finding contours.
                // first use threshold
                gocv.Threshold(imgDelta, &imgThresh, 25, 255, gocv.ThresholdBinary)

                // then dilate
                kernel := gocv.GetStructuringElement(gocv.MorphRect, image.Pt(3, 3))
                defer kernel.Close()
                gocv.Dilate(imgThresh, &imgThresh, kernel)

                // now find contours
                contours := gocv.FindContours(imgThresh, gocv.RetrievalExternal, gocv.ChainApproxSimple)
                for i, c := range contours {
                        area := gocv.ContourArea(c)
                        if area < MinimumArea {
                                continue
                        }

                        status = "Motion detected : " 
                        fmt.Println(status , i , "Area : ", area)
                }

        }
}```


## Your Environment
* Operating System and version: macOS Sierra
* OpenCV version used: opencv 3.4.2
* How did you install OpenCV? brew install opencv
* GoCV version used: gocv version: 0.16.0
* Go version: go version go1.10 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by deadprogram** [comment]
Hello @gesaleh you would need to provide the entire program for us to be able to help you. Seems like you pasted the example code itself without modification.

**Comment by gesaleh** [comment]
please find the program
minor modification just added save image after stabilisation period (100 changes)

```package main

import (
        "fmt"
        "image"
        "os"
        "gocv.io/x/gocv"
)

const MinimumArea = 3000

func main() {
        if len(os.Args) < 2 {
                fmt.Println("How to run:\n\tmotion-detect [camera ID]")
                return
        }

        // parse args
        deviceID := os.Args[1]
        saveFile := os.Args[2]

        webcam, err := gocv.OpenVideoCapture(deviceID)
        if err != nil {
                fmt.Printf("Error opening video capture device: %v\n", deviceID)
                return
        }
        defer webcam.Close()

        img := gocv.NewMat()
        defer img.Close()

        imgDelta := gocv.NewMat()
        defer imgDelta.Close()

        imgThresh := gocv.NewMat()
        defer imgThresh.Close()

        mog2 := gocv.NewBackgroundSubtractorMOG2()
        defer mog2.Close()

        status := "Ready"

        fmt.Printf("Start reading device: %v\n", deviceID)
        stable := 0
        for {
                if ok := webcam.Read(&img); !ok {
                        fmt.Printf("Device closed: %v\n", deviceID)
                        return
                }
                if img.Empty() {
                        continue
                }

                status = "Ready"
                //statusColor := color.RGBA{0, 255, 0, 0}

                // first phase of cleaning up image, obtain foreground only
                mog2.Apply(img, &imgDelta)

                // remaining cleanup of the image to use for finding contours.
                // first use threshold
                gocv.Threshold(imgDelta, &imgThresh, 25, 255, gocv.ThresholdBinary)

                // then dilate
                kernel := gocv.GetStructuringElement(gocv.MorphRect, image.Pt(3, 3))
                defer kernel.Close()
                gocv.Dilate(imgThresh, &imgThresh, kernel)

                // now find contours
                contours := gocv.FindContours(imgThresh, gocv.RetrievalExternal, gocv.ChainApproxSimple)
                for i, c := range contours {
                        area := gocv.ContourArea(c)
                        if area < MinimumArea {
                                continue
                        }

                        status = "Motion detected : " 
                        if stable > 100 { 
                                gocv.IMWrite(saveFile, img)
                        }
                        fmt.Println(status , i , "Area : ", area, " stable :" , stable)
                }
                stable += 1

        }
}`

**Comment by deadprogram** [comment]
Hi @gesaleh I think the logic in this program is incorrect. You probably want to move the ` gocv.IMWrite(saveFile, img)` to outside of the `for i, c := range contours {` loop. Otherwise it will try to save that file once per contour.

**Comment by gesaleh** [comment]
understood my issue 
I wasn't giving extension to file (image) once i gave it jpg it works

**Comment by gesaleh** [comment]
question concerning the logic since i do not display the image is there an image delta that give the area difference ? (like in python with numpy arrays) ?

**Comment by deadprogram** [comment]
Sorry I do not fully understand your question. Perhaps you want to save the value for `area` for each iteration and compare that?
