### ISSUE TITLE
nextEventMatchingMask should only be called from the Main Thread!

### ISSUE THREAD

**Issue by xiaocode** [hybridgroup/gocv#302]
When I run go run main.go,It exited with messsage: "nextEventMatchingMask should only be called from the Main Thread!"
## Description

2018-09-21 03:08:38.006 main[6030:197963] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3a7d82db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6197fc76 objc_exception_throw + 48
	2   AppKit                              0x00007fff38484297 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4167
	3   libopencv_highgui.3.4.dylib         0x0000000005796b11 cvWaitKey + 351
	4   libopencv_highgui.3.4.dylib         0x000000000579241e _ZN2cv9waitKeyExEi + 34
	5   libopencv_highgui.3.4.dylib         0x0000000005792484 _ZN2cv7waitKeyEi + 34
	6   main                                0x00000000040a67bc _cgo_15112270eda1_Cfunc_Window_WaitKey + 28
	7   main                                0x0000000004053760 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff626e9b66 m=7 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40a67a0, 0xc00060be58, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc00060be20 sp=0xc00060bde8 pc=0x40050ce
gocv.io/x/gocv._Cfunc_Window_WaitKey(0x0, 0xc000000000)
	_cgo_gotypes.go:4712 +0x4d fp=0xc00060be58 sp=0xc00060be20 pc=0x409d9bd
gocv.io/x/gocv.(*Window).WaitKey(0xc00008c400, 0x0, 0xc00060bf28)
	/Users/apple/go/src/gocv.io/x/gocv/highgui.go:170 +0x2a fp=0xc00060be78 sp=0xc00060be58 pc=0x409e19a
main.main()
	/Users/apple/Documents/Gitlab/casino/godock/gocv/src/main.go:57 +0x19b fp=0xc00060bf98 sp=0xc00060be78 pc=0x40a3e6b
runtime.main()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201 +0x207 fp=0xc00060bfe0 sp=0xc00060bf98 pc=0x402bb97
runtime.goexit()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00060bfe8 sp=0xc00060bfe0 pc=0x4053fc1

rax    0x0
rbx    0x700008ceb000
rcx    0x700008ce9468
rdx    0x0
rdi    0x11c03
rsi    0x6
rbp    0x700008ce94a0
rsp    0x700008ce9468
r8     0x700008ce9330
r9     0x700008ce9500
r10    0x0
r11    0x206
r12    0x11c03
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff626e9b66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2

## Your Environment

* Operating System and version: MacOS 10.13.6
* OpenCV version used:  3.4.2
* GoCV version used:  0.16.0
* Go version: go1.11 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
When on macOS, you must perform any window operations in the main thread, not inside any goroutines. This is generally the problem when encountering this type off error.
