### ISSUE TITLE
gocv.MinMaxIdx corrupts memory leading to crash

### ISSUE THREAD

**Issue by usedbytes** [hybridgroup/gocv#334]
## Description

I've been tracking down random segfaults in my application, caused by `gocv.MinMaxIdx`. It looks like the implementation of this function is wrong, causing random corruption and eventually crashes in the runtime (or elsewhere).

## Steps to Reproduce

I eventually tracked it down to the following minimal reproducer, which tends to segfault on my system(s) in < 2s (sometimes you get lucky and it runs OK):

```
package main

import (
	"gocv.io/x/gocv"
)

func main() {
	for {
		src := gocv.NewMatWithSize(1, 16, gocv.MatTypeCV8U)
		_, _, _, _ = gocv.MinMaxIdx(src)
		src.Close()
	}
}
```
Example crash (though it's random corruption, so the crashes vary):
```
$ time go run crash.go
runtime: gp: gp=0xc000000000, goid=0, gp->atomicstatus=0
runtime:  g:  g=0xc000062180, goid=0,  g->atomicstatus=0
fatal error: stopg: invalid status

runtime stack:
runtime.throw(0x4cf1c7, 0x15)
        /usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.scang(0xc000000000, 0xc000025270)
        /usr/lib/go/src/runtime/proc.go:930 +0x3ad
runtime.markroot.func1()
        /usr/lib/go/src/runtime/mgcmark.go:264 +0x6d
runtime.markroot(0xc000025270, 0xc000000006)
        /usr/lib/go/src/runtime/mgcmark.go:245 +0x309
runtime.gcDrain(0xc000025270, 0xd)
        /usr/lib/go/src/runtime/mgcmark.go:882 +0x117
runtime.gcBgMarkWorker.func2()
        /usr/lib/go/src/runtime/mgc.go:1862 +0x18a
runtime.systemstack(0xc000062180)
        /usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1229

goroutine 19 [GC worker (idle)]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc000032f60 sp=0xc000032f58 pc=0x465130
runtime.gcBgMarkWorker(0xc000024000)
        /usr/lib/go/src/runtime/mgc.go:1826 +0x1b8 fp=0xc000032fd8 sp=0xc000032f60 pc=0x42e6e8
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000032fe0 sp=0xc000032fd8 pc=0x467211
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go/src/runtime/mgc.go:1720 +0x77

goroutine 0 [idle]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45b219]

runtime stack:
runtime.throw(0x4d2410, 0x2a)
        /usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:374 +0x2f2
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000000, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/runtime/traceback.go:161 +0x179
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000000, 0x0)
        /usr/lib/go/src/runtime/traceback.go:719 +0xf3
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000000)
        /usr/lib/go/src/runtime/traceback.go:673 +0x52
runtime.tracebackothers(0xc000062180)
        /usr/lib/go/src/runtime/traceback.go:938 +0x187
runtime.dopanic_m(0xc000062180, 0x43d7e2, 0x7f8647ffe9d8, 0x1)
        /usr/lib/go/src/runtime/panic.go:805 +0x2aa
runtime.fatalthrow.func1()
        /usr/lib/go/src/runtime/panic.go:663 +0x5f
runtime.fatalthrow()
        /usr/lib/go/src/runtime/panic.go:660 +0x57
runtime.throw(0x4cf1c7, 0x15)
        /usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.scang(0xc000000000, 0xc000025270)
        /usr/lib/go/src/runtime/proc.go:930 +0x3ad
runtime.markroot.func1()
        /usr/lib/go/src/runtime/mgcmark.go:264 +0x6d
runtime.markroot(0xc000025270, 0xc000000006)
        /usr/lib/go/src/runtime/mgcmark.go:245 +0x309
runtime.gcDrain(0xc000025270, 0xd)
        /usr/lib/go/src/runtime/mgcmark.go:882 +0x117
runtime.gcBgMarkWorker.func2()
        /usr/lib/go/src/runtime/mgc.go:1862 +0x18a
runtime.systemstack(0xc000062180)
        /usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1229
exit status 2

real    0m1.331s
user    0m1.215s
sys     0m0.169s
```

## Cause

I checked the [documentation for minMaxIdx](https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#minmaxidx) and it says this:

> Note When minIdx is not NULL, it must have at least 2 elements (as well as maxIdx), even if src is a single-row or single-column matrix. In OpenCV (following MATLAB) each array has at least 2 dimensions, i.e. single-column matrix is Mx1 matrix (and therefore minIdx/maxIdx will be (i1,0)/(i2,0)) and single-row matrix is 1xN matrix (and therefore minIdx/maxIdx will be (0,j1)/(0,j2)).

So, `gocv` is passing pointers to single `C.int`s to the function, but the function expects two element arrays, so whatever comes just after `cMaxIdx` must be getting trashed.

The following patch fixes the crash, but it's not obviously correct (because 2D indices are probably what the function should return). I didn't want to change the function signature, but returning an `image.Point` or other 2D structure would probably be the most correct thing (my version won't return the right value for single-row matrices, or 2D matrices). Happy to submit a patch if you have a preference for what to do.

```
diff --git a/core.go b/core.go
index 79b8cf3..9934d29 100644
--- a/core.go
+++ b/core.go
@@ -1281,12 +1281,12 @@ func Min(src1, src2 Mat, dst *Mat) {
 func MinMaxIdx(input Mat) (minVal, maxVal float32, minIdx, maxIdx int) {
 	var cMinVal C.double
 	var cMaxVal C.double
-	var cMinIdx C.int
-	var cMaxIdx C.int
+	var cMinIdx []C.int = []C.int{ 0, 0 }
+	var cMaxIdx []C.int = []C.int{ 0, 0 }
 
-	C.Mat_MinMaxIdx(input.p, &cMinVal, &cMaxVal, &cMinIdx, &cMaxIdx)
+	C.Mat_MinMaxIdx(input.p, &cMinVal, &cMaxVal, &cMinIdx[0], &cMaxIdx[0])
 
-	return float32(cMinVal), float32(cMaxVal), int(minIdx), int(maxIdx)
+	return float32(cMinVal), float32(cMaxVal), int(cMinIdx[0]), int(cMaxIdx[0])
 }
 
 // MinMaxLoc finds the global minimum and maximum in an array.
```
I didn't do an audit of the other similar functions, but there might be other functions which are affected.

**Comment by skytodmoon** [comment]
The same memory leak with gocv 0.26
`gocv.io/x/gocv.MinMaxLoc
/Users/bob/go/pkg/mod/gocv.io/x/gocv@v0.27.0/core.go

  Total:        33MB       33MB (flat, cum)  0.19%
   1496            .          .           // 
   1497            .          .           // For further details, please see: 
   1498            .          .           // https://docs.opencv.org/trunk/d2/de8/group__core__array.html#gab473bf2eb6d14ff97e89b355dac20707 
   1499            .          .           // 
   1500            .          .           func MinMaxLoc(input Mat) (minVal, maxVal float32, minLoc, maxLoc image.Point) { 
   1501      10.50MB    10.50MB           	var cMinVal C.double 
   1502          5MB        5MB           	var cMaxVal C.double 
   1503      11.50MB    11.50MB           	var cMinLoc C.struct_Point 
   1504          6MB        6MB           	var cMaxLoc C.struct_Point 
   1505            .          .            
   1506            .          .           	C.Mat_MinMaxLoc(input.p, &cMinVal, &cMaxVal, &cMinLoc, &cMaxLoc) 
   1507            .          .            
   1508            .          .           	minLoc = image.Pt(int(cMinLoc.x), int(cMinLoc.y)) 
   1509            .          .           	maxLoc = image.Pt(int(cMaxLoc.x), int(cMaxLoc.y)) `
