### ISSUE TITLE
Exception throws when debugging the code in vscode. 

### ISSUE THREAD

**Issue by sshxmz** [hybridgroup/gocv#496]
## Description
Exception throws when starting my simple go program with debuging or without debuging. 
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0) /tmp/opencv/opencv-4.1.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor
```
Above exception is thrown in vscode.
If I run it in command line: `go run main.go aaa.png`, no error report but I found the program exit abnormally.
If I build it and run the binary built, it work very well: `go build && ./test aaa.png`

## The simple code:
```
package main
import (
	"image"
	"image/color"
	"gocv.io/x/gocv"
)

func main() {
	img := gocv.IMRead(os.Args[1], gocv.IMReadGrayScale)
	defer img.Close()
	gocv.MedianBlur(img, &img, 5)
	cimg := gocv.NewMat()
	defer cimg.Close()
	gocv.CvtColor(img, &cimg, gocv.ColorGrayToBGR)
        ...
```

## Your Environment
* OS: Ubuntu 16.04 or Win10
* OpenCV version: 4.1.0
* opencv Build:
For Ubuntu, download the source and make it;
For Windows, it is built by mingw by myself, also I tried the downloaded prebuilt opencv from https://github.com/huihut/OpenCV-MinGW-Build
* GoCV version used: 
```
$ go run cmd/version/main.go
gocv version: 0.20.0
opencv lib version: 4.1.0
```
* Go version:
```
$ go version
go version go1.10.4 linux/amd64
```

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?: Never.
* vscode version:
1.37.0.

* gcc and version:
For Ubuntu:
```
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```
For Windows:
```
$ gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 7.3.0
```

### Exception details (For Ubuntu):
```
API server listening at: 127.0.0.1:43031
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0) /tmp/opencv/opencv-4.1.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
SIGABRT: abort
PC=0x7f4c677c4428 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f4c677c4428
stack: frame={sp:0x7fff7c2780e8, fp:0x0} stack=[0x7fff7ba79650,0x7fff7c278680)
00007fff7c277fe8:  7270676d692f7365  000000c4200140c0 
00007fff7c277ff8:  000000000000001a  000000c4200160c0 
00007fff7c278008:  0000000000000021  000000c42001e0c0 
00007fff7c278018:  0000000000000033  000000c4200140e0 
00007fff7c278028:  0000000000000011  000000c420014100 
00007fff7c278038:  0000000000000014  000000c4200160f0 
00007fff7c278048:  0000000000000024  000000c420016120 
00007fff7c278058:  0000000000000023  000000c4200140e0 
00007fff7c278068:  0000000000000011  000000c420014100 
00007fff7c278078:  0000000000000014  0000000000000002 
00007fff7c278088:  0000000000000000  0000000000000000 
00007fff7c278098:  0000000000000000  0000000000000000 
00007fff7c2780a8:  0000000000000000  0000000000000000 
00007fff7c2780b8:  00000000026185f0  00007f4c67b54700 
00007fff7c2780c8:  00000000025f3f30  0000000002619768 
00007fff7c2780d8:  00000000026197b0  0000000002619940 
00007fff7c2780e8: <00007f4c677c602a  0000000000000020 
00007fff7c2780f8:  0000000000000000  0000000000000000 
00007fff7c278108:  0000000000000000  0000000000000000 
00007fff7c278118:  0000000000000000  0000000000000000 
00007fff7c278128:  0000000000000000  0000000000000000 
00007fff7c278138:  0000000000000000  0000000000000000 
00007fff7c278148:  0000000000000000  0000000000000000 
00007fff7c278158:  0000000000000000  0000000000000000 
00007fff7c278168:  0000000000000000  0000000000000000 
00007fff7c278178:  0000000000000000  0000000000000000 
00007fff7c278188:  0000000000000000  0000000000000000 
00007fff7c278198:  0000000000000000  0000000000000000 
00007fff7c2781a8:  0000000000000000  0000000000000000 
00007fff7c2781b8:  0000000000000000  0000000000000000 
00007fff7c2781c8:  0000000000000000  0000000000000000 
00007fff7c2781d8:  0000000000000000  0000000000000000 
runtime: unknown pc 0x7f4c677c4428
stack: frame={sp:0x7fff7c2780e8, fp:0x0} stack=[0x7fff7ba79650,0x7fff7c278680)
00007fff7c277fe8:  7270676d692f7365  000000c4200140c0 
00007fff7c277ff8:  000000000000001a  000000c4200160c0 
00007fff7c278008:  0000000000000021  000000c42001e0c0 
00007fff7c278018:  0000000000000033  000000c4200140e0 
00007fff7c278028:  0000000000000011  000000c420014100 
00007fff7c278038:  0000000000000014  000000c4200160f0 
00007fff7c278048:  0000000000000024  000000c420016120 
00007fff7c278058:  0000000000000023  000000c4200140e0 
00007fff7c278068:  0000000000000011  000000c420014100 
00007fff7c278078:  0000000000000014  0000000000000002 
00007fff7c278088:  0000000000000000  0000000000000000 
00007fff7c278098:  0000000000000000  0000000000000000 
00007fff7c2780a8:  0000000000000000  0000000000000000 
00007fff7c2780b8:  00000000026185f0  00007f4c67b54700 
00007fff7c2780c8:  00000000025f3f30  0000000002619768 
00007fff7c2780d8:  00000000026197b0  0000000002619940 
00007fff7c2780e8: <00007f4c677c602a  0000000000000020 
00007fff7c2780f8:  0000000000000000  0000000000000000 
00007fff7c278108:  0000000000000000  0000000000000000 
00007fff7c278118:  0000000000000000  0000000000000000 
00007fff7c278128:  0000000000000000  0000000000000000 
00007fff7c278138:  0000000000000000  0000000000000000 
00007fff7c278148:  0000000000000000  0000000000000000 
00007fff7c278158:  0000000000000000  0000000000000000 
00007fff7c278168:  0000000000000000  0000000000000000 
00007fff7c278178:  0000000000000000  0000000000000000 
00007fff7c278188:  0000000000000000  0000000000000000 
00007fff7c278198:  0000000000000000  0000000000000000 
00007fff7c2781a8:  0000000000000000  0000000000000000 
00007fff7c2781b8:  0000000000000000  0000000000000000 
00007fff7c2781c8:  0000000000000000  0000000000000000 
00007fff7c2781d8:  0000000000000000  0000000000000000 

goroutine 1 [syscall]:
runtime.cgocall(0x4bd3ac, 0xc420077de0, 0xc420070100)
	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc420077d90 sp=0xc420077d58 pc=0x41a624
gocv.io/x/gocv._Cfunc_CvtColor(0x261e5e0, 0x263ea70, 0x8)
	_cgo_gotypes.go:1232 +0x45 fp=0xc420077de0 sp=0xc420077d90 pc=0x4b8725
gocv.io/x/gocv.CvtColor.func1(0x261e5e0, 0x263ea70, 0xc400000008)
	/home/sshxmz/gopath/src/gocv.io/x/gocv/imgproc.go:85 +0xa1 fp=0xc420077e28 sp=0xc420077de0 pc=0x4b9e21
gocv.io/x/gocv.CvtColor(0x261e5e0, 0xc420077f18, 0x8)
	/home/sshxmz/gopath/src/gocv.io/x/gocv/imgproc.go:85 +0x43 fp=0xc420077e50 sp=0xc420077e28 pc=0x4b96d3
main.main()
	/home/sshxmz/gopath/src/local/findcircles/main.go:24 +0x1f8 fp=0xc420077f88 sp=0xc420077e50 pc=0x4ba5c8
runtime.main()
	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x1d0 fp=0xc420077fe0 sp=0xc420077f88 pc=0x445000
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420077fe8 sp=0xc420077fe0 pc=0x46dcd1
rax    0x0
rbx    0x26185f0
rcx    0x7f4c677c4428
rdx    0x6
rdi    0x4ebd
rsi    0x4ebd
rbp    0x7f4c67b54700
rsp    0x7fff7c2780e8
r8     0x7f4c67b55770
r9     0x7f4c6e973a80
r10    0x8
r11    0x206
r12    0x25f3f30
r13    0x2619768
r14    0x26197b0
r15    0x2619940
rip    0x7f4c677c4428
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
Process exiting with code: 0
```

Exception is come from assertion at `imgproc\src\color.cpp:cvtColor()`
```cpp
void cvtColor( InputArray _src, OutputArray _dst, int code, int dcn )
{
    CV_INSTRUMENT_REGION();

    CV_Assert(!_src.empty());

    if(dcn <= 0)
            dcn = dstChannels(code);
```

**Comment by sshxmz** [comment]
> ## Description
> Exception throws when starting my simple go program with debuging or without debuging.
> 
> ```
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(4.1.0) /tmp/opencv/opencv-4.1.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor
> ```
> 
> Above exception is thrown in vscode.
> If I run it in command line: `go run main.go aaa.png`, no error report but I found the program exit abnormally.
> If I build it and run the binary built, it work very well: `go build && ./test aaa.png`
> 
> ## The simple code:
> ```
> package main
> import (
> 	"image"
> 	"image/color"
> 	"gocv.io/x/gocv"
> )
> 
> func main() {
> 	img := gocv.IMRead(os.Args[1], gocv.IMReadGrayScale)
> 	defer img.Close()
> 	gocv.MedianBlur(img, &img, 5)
> 	cimg := gocv.NewMat()
> 	defer cimg.Close()
> 	gocv.CvtColor(img, &cimg, gocv.ColorGrayToBGR)
>         ...
> ```
> 
> ## Your Environment
> * OS: Ubuntu 16.04 or Win10
> * OpenCV version: 4.1.0
> * opencv Build:
>   For Ubuntu, download the source and make it;
>   For Windows, it is built by mingw by myself, also I tried the downloaded prebuilt opencv from https://github.com/huihut/OpenCV-MinGW-Build
> * GoCV version used:
> 
> ```
> $ go run cmd/version/main.go
> gocv version: 0.20.0
> opencv lib version: 4.1.0
> ```
> 
> * Go version:
> 
> ```
> $ go version
> go version go1.10.4 linux/amd64
> ```
> 
> * Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?: Never.
> * vscode version:
>   1.37.0.
> * gcc and version:
>   For Ubuntu:
> 
> ```
> gcc --version
> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> ```
> 
> For Windows:
> 
> ```
> $ gcc --version
> gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 7.3.0
> ```
> 
> ### Exception details (For Ubuntu):
> ```
> API server listening at: 127.0.0.1:43031
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(4.1.0) /tmp/opencv/opencv-4.1.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
> SIGABRT: abort
> PC=0x7f4c677c4428 m=0 sigcode=18446744073709551610
> 
> goroutine 0 [idle]:
> runtime: unknown pc 0x7f4c677c4428
> stack: frame={sp:0x7fff7c2780e8, fp:0x0} stack=[0x7fff7ba79650,0x7fff7c278680)
> 00007fff7c277fe8:  7270676d692f7365  000000c4200140c0 
> 00007fff7c277ff8:  000000000000001a  000000c4200160c0 
> 00007fff7c278008:  0000000000000021  000000c42001e0c0 
> 00007fff7c278018:  0000000000000033  000000c4200140e0 
> 00007fff7c278028:  0000000000000011  000000c420014100 
> 00007fff7c278038:  0000000000000014  000000c4200160f0 
> 00007fff7c278048:  0000000000000024  000000c420016120 
> 00007fff7c278058:  0000000000000023  000000c4200140e0 
> 00007fff7c278068:  0000000000000011  000000c420014100 
> 00007fff7c278078:  0000000000000014  0000000000000002 
> 00007fff7c278088:  0000000000000000  0000000000000000 
> 00007fff7c278098:  0000000000000000  0000000000000000 
> 00007fff7c2780a8:  0000000000000000  0000000000000000 
> 00007fff7c2780b8:  00000000026185f0  00007f4c67b54700 
> 00007fff7c2780c8:  00000000025f3f30  0000000002619768 
> 00007fff7c2780d8:  00000000026197b0  0000000002619940 
> 00007fff7c2780e8: <00007f4c677c602a  0000000000000020 
> 00007fff7c2780f8:  0000000000000000  0000000000000000 
> 00007fff7c278108:  0000000000000000  0000000000000000 
> 00007fff7c278118:  0000000000000000  0000000000000000 
> 00007fff7c278128:  0000000000000000  0000000000000000 
> 00007fff7c278138:  0000000000000000  0000000000000000 
> 00007fff7c278148:  0000000000000000  0000000000000000 
> 00007fff7c278158:  0000000000000000  0000000000000000 
> 00007fff7c278168:  0000000000000000  0000000000000000 
> 00007fff7c278178:  0000000000000000  0000000000000000 
> 00007fff7c278188:  0000000000000000  0000000000000000 
> 00007fff7c278198:  0000000000000000  0000000000000000 
> 00007fff7c2781a8:  0000000000000000  0000000000000000 
> 00007fff7c2781b8:  0000000000000000  0000000000000000 
> 00007fff7c2781c8:  0000000000000000  0000000000000000 
> 00007fff7c2781d8:  0000000000000000  0000000000000000 
> runtime: unknown pc 0x7f4c677c4428
> stack: frame={sp:0x7fff7c2780e8, fp:0x0} stack=[0x7fff7ba79650,0x7fff7c278680)
> 00007fff7c277fe8:  7270676d692f7365  000000c4200140c0 
> 00007fff7c277ff8:  000000000000001a  000000c4200160c0 
> 00007fff7c278008:  0000000000000021  000000c42001e0c0 
> 00007fff7c278018:  0000000000000033  000000c4200140e0 
> 00007fff7c278028:  0000000000000011  000000c420014100 
> 00007fff7c278038:  0000000000000014  000000c4200160f0 
> 00007fff7c278048:  0000000000000024  000000c420016120 
> 00007fff7c278058:  0000000000000023  000000c4200140e0 
> 00007fff7c278068:  0000000000000011  000000c420014100 
> 00007fff7c278078:  0000000000000014  0000000000000002 
> 00007fff7c278088:  0000000000000000  0000000000000000 
> 00007fff7c278098:  0000000000000000  0000000000000000 
> 00007fff7c2780a8:  0000000000000000  0000000000000000 
> 00007fff7c2780b8:  00000000026185f0  00007f4c67b54700 
> 00007fff7c2780c8:  00000000025f3f30  0000000002619768 
> 00007fff7c2780d8:  00000000026197b0  0000000002619940 
> 00007fff7c2780e8: <00007f4c677c602a  0000000000000020 
> 00007fff7c2780f8:  0000000000000000  0000000000000000 
> 00007fff7c278108:  0000000000000000  0000000000000000 
> 00007fff7c278118:  0000000000000000  0000000000000000 
> 00007fff7c278128:  0000000000000000  0000000000000000 
> 00007fff7c278138:  0000000000000000  0000000000000000 
> 00007fff7c278148:  0000000000000000  0000000000000000 
> 00007fff7c278158:  0000000000000000  0000000000000000 
> 00007fff7c278168:  0000000000000000  0000000000000000 
> 00007fff7c278178:  0000000000000000  0000000000000000 
> 00007fff7c278188:  0000000000000000  0000000000000000 
> 00007fff7c278198:  0000000000000000  0000000000000000 
> 00007fff7c2781a8:  0000000000000000  0000000000000000 
> 00007fff7c2781b8:  0000000000000000  0000000000000000 
> 00007fff7c2781c8:  0000000000000000  0000000000000000 
> 00007fff7c2781d8:  0000000000000000  0000000000000000 
> 
> goroutine 1 [syscall]:
> runtime.cgocall(0x4bd3ac, 0xc420077de0, 0xc420070100)
> 	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc420077d90 sp=0xc420077d58 pc=0x41a624
> gocv.io/x/gocv._Cfunc_CvtColor(0x261e5e0, 0x263ea70, 0x8)
> 	_cgo_gotypes.go:1232 +0x45 fp=0xc420077de0 sp=0xc420077d90 pc=0x4b8725
> gocv.io/x/gocv.CvtColor.func1(0x261e5e0, 0x263ea70, 0xc400000008)
> 	/home/sshxmz/gopath/src/gocv.io/x/gocv/imgproc.go:85 +0xa1 fp=0xc420077e28 sp=0xc420077de0 pc=0x4b9e21
> gocv.io/x/gocv.CvtColor(0x261e5e0, 0xc420077f18, 0x8)
> 	/home/sshxmz/gopath/src/gocv.io/x/gocv/imgproc.go:85 +0x43 fp=0xc420077e50 sp=0xc420077e28 pc=0x4b96d3
> main.main()
> 	/home/sshxmz/gopath/src/local/findcircles/main.go:24 +0x1f8 fp=0xc420077f88 sp=0xc420077e50 pc=0x4ba5c8
> runtime.main()
> 	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x1d0 fp=0xc420077fe0 sp=0xc420077f88 pc=0x445000
> runtime.goexit()
> 	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420077fe8 sp=0xc420077fe0 pc=0x46dcd1
> rax    0x0
> rbx    0x26185f0
> rcx    0x7f4c677c4428
> rdx    0x6
> rdi    0x4ebd
> rsi    0x4ebd
> rbp    0x7f4c67b54700
> rsp    0x7fff7c2780e8
> r8     0x7f4c67b55770
> r9     0x7f4c6e973a80
> r10    0x8
> r11    0x206
> r12    0x25f3f30
> r13    0x2619768
> r14    0x26197b0
> r15    0x2619940
> rip    0x7f4c677c4428
> rflags 0x206
> cs     0x33
> fs     0x0
> gs     0x0
> Process exiting with code: 0
> ```
> 
> Exception is come from assertion at `imgproc\src\color.cpp:cvtColor()`
> 
> ```c++
> void cvtColor( InputArray _src, OutputArray _dst, int code, int dcn )
> {
>     CV_INSTRUMENT_REGION();
> 
>     CV_Assert(!_src.empty());
> 
>     if(dcn <= 0)
>             dcn = dstChannels(code);
> ```

Sorry, I made a mistake in my vscode launch.json settings. The input picture path was wrong.
So please close this issue directly please. Thank you very much!
