### ISSUE TITLE
gocv/cmd/dnn-pose-detection/main.go not working...throws error

### ISSUE THREAD

**Issue by kannan2106** [hybridgroup/gocv#500]
gocv/cmd/dnn-pose-detection/main.go not working...throws error

goroutine 5 [syscall]:
gocv.io/x/gocv._Cfunc_Net_Forward(0x4a61560, 0x4d67170, 0x0)
        _cgo_gotypes.go:4350 +0x55
gocv.io/x/gocv.(*Net).Forward.func2(0xc000006088, 0x4d67170, 0x4d67170)
        C:/Users/K/Downloads/gocv-master/gocv-master/dnn.go:151 +0x6f
gocv.io/x/gocv.(*Net).Forward(0xc000006088, 0x0, 0x0, 0x0)
        C:/Users/K/Downloads/gocv-master/gocv-master/dnn.go:151 +0x84
main.performDetection()
        C:/Users/K/Downloads/gocv-master/gocv-master/cmd/dnn-pose-detection/main.go:149 +0x428
created by main.main
        C:/Users/K/Downloads/gocv-master/gocv-master/cmd/dnn-pose-detection/main.go:99 +0x43f

goroutine 1 [syscall, locked to thread]:
gocv.io/x/gocv._Cfunc_VideoCapture_Read(0x805a50, 0x4a622c0, 0x0)
        _cgo_gotypes.go:5146 +0x54
gocv.io/x/gocv.(*VideoCapture).Read.func1(0xc000006080, 0xc000069ed8, 0xc000069e28)
        C:/Users/K/Downloads/gocv-master/gocv-master/videoio.go:218 +0xab
gocv.io/x/gocv.(*VideoCapture).Read(0xc000006080, 0xc000069ed8, 0xc000018000)
        C:/Users/K/Downloads/gocv-master/gocv-master/videoio.go:218 +0x3c
main.main()
        C:/Users/K/Downloads/gocv-master/gocv-master/cmd/dnn-pose-detection/main.go:102 +0x45d

**Comment by deadprogram** [comment]
Is your installation of GoCV working otherwise, @kannan2106 ?

**Comment by deadprogram** [comment]
Closing due to inactivity... please reopen if needed. Thank you.

**Comment by YamiOdymel** [comment]
Same issue.

```
C:\Users\YamiOdymel\go\src\gocv.io\x\gocv>go run ./cmd/dnn-pose-detection/main.go 0 C:\Users\YamiOdymel\Downloads\pose_iter_440000.caffemodel C:\Users\YamiOdymel\Downloads\openpose_pose_coco.prototxt.txt openvino fp16
# gocv.io/x/gocv
dnn.cpp: In function 'cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)':
dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1 of 'cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]' [-Wconversion-null]
         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
                                                                                                      ^
Start reading device: 0
Exception 0x20474343 0x5488d20 0x6161616161616161 0x7ffbf829a839
PC=0x7ffbf829a839

runtime: unknown pc 0x7ffbf829a839
stack: frame={sp:0x477ef60, fp:0x0} stack=[0x0,0x477fe80)
000000000477ee60:  0000000000000000  0000000000a16640
000000000477ee70:  0000000000000000  0000000000000000
000000000477ee80:  0000000000000000  0000000000000000
000000000477ee90:  0000000000000000  0000000000000000
000000000477eea0:  0000000000000000  0000000000000000
000000000477eeb0:  0000000000000000  0000000000000000
000000000477eec0:  0000000000000000  0000000000000000
000000000477eed0:  0000000000000000  0000000000000000
000000000477eee0:  000089a1ce7c7e6c  000000000477eef8
000000000477eef0:  0000000000000067  0000000000000a98
000000000477ef00:  00000000051f2870  0000000000000a98
000000000477ef10:  0000000000000a98  00007ffbf8284a15
000000000477ef20:  0000000000000008  00000000013d79c0
000000000477ef30:  000089a1ce7c7dcc  000000000477ef70
000000000477ef40:  0000000001429624  0000000005488d60
000000000477ef50:  0000000005488da0  00007ffbf829a839
000000000477ef60: <000000000000c016  0000000005488d20
000000000477ef70:  000000000128e7f0  5f2d326d64742d6d
000000000477ef80:  0000000020474343  0000000000000000
000000000477ef90:  00007ffbf829a839  6161616100000001
000000000477efa0:  0000000005488d20  6161616161616161
000000000477efb0:  6161616161616161  4161416161616161
000000000477efc0:  4141414141616161  6161614161416161
000000000477efd0:  0061616141414161  0000000000000000
000000000477efe0:  0000000000000000  0000002701429624
000000000477eff0:  000000006c0301d2  000000000141a9f0
000000000477f000:  000000000128e7f0  0000000001475d20
000000000477f010:  0000000005488dc0  000000006c0301d2
000000000477f020:  0000b849afcba2cd  0000000000000000
000000000477f030:  0000000005488da0  00000000010fed27
000000000477f040:  0000000000000000  000000000128e7f0
000000000477f050:  000000000000002e  00000000013ae9fe
runtime: unknown pc 0x7ffbf829a839
stack: frame={sp:0x477ef60, fp:0x0} stack=[0x0,0x477fe80)
000000000477ee60:  0000000000000000  0000000000a16640
000000000477ee70:  0000000000000000  0000000000000000
000000000477ee80:  0000000000000000  0000000000000000
000000000477ee90:  0000000000000000  0000000000000000
000000000477eea0:  0000000000000000  0000000000000000
000000000477eeb0:  0000000000000000  0000000000000000
000000000477eec0:  0000000000000000  0000000000000000
000000000477eed0:  0000000000000000  0000000000000000
000000000477eee0:  000089a1ce7c7e6c  000000000477eef8
000000000477eef0:  0000000000000067  0000000000000a98
000000000477ef00:  00000000051f2870  0000000000000a98
000000000477ef10:  0000000000000a98  00007ffbf8284a15
000000000477ef20:  0000000000000008  00000000013d79c0
000000000477ef30:  000089a1ce7c7dcc  000000000477ef70
000000000477ef40:  0000000001429624  0000000005488d60
000000000477ef50:  0000000005488da0  00007ffbf829a839
000000000477ef60: <000000000000c016  0000000005488d20
000000000477ef70:  000000000128e7f0  5f2d326d64742d6d
000000000477ef80:  0000000020474343  0000000000000000
000000000477ef90:  00007ffbf829a839  6161616100000001
000000000477efa0:  0000000005488d20  6161616161616161
000000000477efb0:  6161616161616161  4161416161616161
000000000477efc0:  4141414141616161  6161614161416161
000000000477efd0:  0061616141414161  0000000000000000
000000000477efe0:  0000000000000000  0000002701429624
000000000477eff0:  000000006c0301d2  000000000141a9f0
000000000477f000:  000000000128e7f0  0000000001475d20
000000000477f010:  0000000005488dc0  000000006c0301d2
000000000477f020:  0000b849afcba2cd  0000000000000000
000000000477f030:  0000000005488da0  00000000010fed27
000000000477f040:  0000000000000000  000000000128e7f0
000000000477f050:  000000000000002e  00000000013ae9fe

goroutine 19 [syscall]:
gocv.io/x/gocv._Cfunc_Net_BlobFromImage(0x191e230, 0x3f70101010101010, 0x17000000170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:4613 +0x58
gocv.io/x/gocv.BlobFromImage.func1(0x191e230, 0x3f70101010101010, 0x17000000170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101)
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/dnn.go:299 +0xcb
gocv.io/x/gocv.BlobFromImage(0x191e230, 0x3f70101010101010, 0x170, 0x170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/dnn.go:299 +0xa5
main.performDetection()
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/cmd/dnn-pose-detection/main.go:143 +0x3e6
created by main.main
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/cmd/dnn-pose-detection/main.go:99 +0x43f

goroutine 1 [syscall, locked to thread]:
gocv.io/x/gocv._Cfunc_VideoCapture_Read(0x192e8a0, 0x191deb0, 0x0)
        _cgo_gotypes.go:5611 +0x54
gocv.io/x/gocv.(*VideoCapture).Read.func1(0xc00008e070, 0xc00008bed8, 0x49ddaf)
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/videoio.go:218 +0xab
gocv.io/x/gocv.(*VideoCapture).Read(0xc00008e070, 0xc00008bed8, 0xc00004c001)
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/videoio.go:218 +0x3c
main.main()
        C:/Users/YamiOdymel/go/src/gocv.io/x/gocv/cmd/dnn-pose-detection/main.go:102 +0x45d
rax     0x140cc0
rbx     0x5488d20
rcx     0x195
rdi     0x5488d60
rsi     0x128e7f0
rbp     0x5488da0
rsp     0x477ef60
r8      0x7ffbfa5c2bf2
r9      0x9f0000
r10     0x7ffbfa5bba17
r11     0x140000
r12     0x5488dc0
r13     0x6c0301d2
r14     0x1429624
r15     0x0
rip     0x7ffbf829a839
rflags  0x202
cs      0x33
fs      0x53
gs      0x2b
```

`gocv` version

```
C:\Users\YamiOdymel\go\src\gocv.io\x\gocv>go run cmd\version\main.go
# gocv.io/x/gocv
dnn.cpp: In function 'cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)':
dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1 of 'cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]' [-Wconversion-null]
         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
                                                                                                      ^
gocv version: 0.22.0
opencv lib version: 4.2.0
```

**Comment by bus710** [comment]
I do see a similar case so that reopen this issue.

The dnn-detection example works fine with the caffe model but not with tensorflow.

Good case:

```sh
$ cd $GOPATH/src/gocv.io/x/gocv/cmd/dnn-detection

$ wget https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel

$ wget https://raw.githubusercontent.com/opencv/opencv/master/samples/dnn/face_detector/deploy.prototxt

$ go run main.go 0 \
        ./res10_300x300_ssd_iter_140000.caffemodel 
        ./deploy.prototxt 
```

Bad case:

```sh
$ cd $GOPATH/src/gocv.io/x/gocv/cmd/dnn-detection

$ wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz

$ tar -zxvf ssd_mobilenet_v1_coco_2017_11_17.tar.gz

$ mv ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb .

$ wget https://gist.githubusercontent.com/dkurt/45118a9c57c38677b65d6953ae62924a/raw/b0edd9e8c992c25fe1c804e77b06d20a89064871/ssd_mobilenet_v1_coco_2017_11_17.pbtxt

$ go run main.go 0 \
        ./frozen_inference_graph.pb \
        ./ssd_mobilenet_v1_coco_2017_11_17.pbtxt
```

And its error message:

```
# gocv.io/x/gocv
dnn.cpp: In function ‘cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)’:
dnn.cpp:119:76: warning: passing NULL to non-pointer argument 1 of ‘cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]’ [-Wconversion-null]
  119 |         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
      |                                                                            ^~~~
In file included from /usr/local/include/opencv4/opencv2/core.hpp:58,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
                 from dnn.h:7,
                 from dnn.cpp:1:
/usr/local/include/opencv4/opencv2/core/types.hpp:2207:27: note:   declared here
 2207 | Scalar_<_Tp>::Scalar_(_Tp v0)
      |                       ~~~~^~
[ WARN:0] global /tmp/opencv/opencv-4.2.0/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Gtk-Message: 14:07:54.926: Failed to load module "canberra-gtk-module"
Start reading device: 0
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /tmp/opencv/opencv-4.2.0/modules/dnn/src/dnn.cpp:285: error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20191202::blobFromImages(cv::InputArrayOfArrays, cv::OutputArray, double, cv::Size, const Scalar&, bool, bool, int)'
> Scaling is not supported for CV_8U blob depth (expected: 'scalefactor == 1.0'), where
>     'scalefactor' is 0.00784314
> must be equal to
>     '1.0' is 1

SIGABRT: abort
PC=0x7fc80ab9c3eb m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4b5000, 0xc000052c00, 0x41e8c5)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000052ba0 sp=0xc000052b68 pc=0x41e25b
gocv.io/x/gocv._Cfunc_Net_BlobFromImage(0xba8280, 0x3f80101010101010, 0x12c0000012c, 0x405fe00000000000, 0x405fe00000000000, 0x405fe00000000000, 0x0, 0xc000050001, 0x0)
	_cgo_gotypes.go:4656 +0x51 fp=0xc000052c00 sp=0xc000052ba0 pc=0x4aef61
gocv.io/x/gocv.BlobFromImage.func1(0xba8280, 0x3f80101010101010, 0x12c0000012c, 0x405fe00000000000, 0x405fe00000000000, 0x405fe00000000000, 0x0, 0xc000050001, 0x0)
	/home/bus710/go/src/gocv.io/x/gocv/dnn.go:299 +0xc4 fp=0xc000052c58 sp=0xc000052c00 pc=0x4b1774
gocv.io/x/gocv.BlobFromImage(0xba8280, 0x3f80101010101010, 0x12c, 0x12c, 0x405fe00000000000, 0x405fe00000000000, 0x405fe00000000000, 0x0, 0x1, 0x0)
	/home/bus710/go/src/gocv.io/x/gocv/dnn.go:299 +0x9e fp=0xc000052cb0 sp=0xc000052c58 pc=0x4b032e
main.main()
	/home/bus710/go/src/gocv.io/x/gocv/cmd/dnn-detection/main.go:111 +0x513 fp=0xc000052f60 sp=0xc000052cb0 pc=0x4b2a03
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc000052fe0 sp=0xc000052f60 pc=0x446b0e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x46f151

rax    0x0
rbx    0x7fc80106ce40
rcx    0x7fc80ab9c3eb
rdx    0x0
rdi    0x2
rsi    0x7ffdbc93b6d0
rbp    0x90a460
rsp    0x7ffdbc93b6d0
r8     0x0
r9     0x7ffdbc93b6d0
r10    0x8
r11    0x246
r12    0xbc7df0
r13    0x7fc80b421ac0
r14    0xb9cee0
r15    0x7ffdbc93b9c0
rip    0x7fc80ab9c3eb
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by bus710** [comment]
I see that the **blob from image** can be the key to solve this issue.

I was rearranging the example code with my own image file and the initial parameter of that function was image.Pt(300,300) in the original code. I had the issue as my previous comment but it is now okay with the value of image.Pt(256, 256). This may not the exact solution for others but worth to try.
