### ISSUE TITLE
Error with Tensorflow model: Not enough memory to run on this device.

### ISSUE THREAD

**Issue by twatzl** [hybridgroup/gocv#515]
Hi. When using gocv for evaluating  a TensorFlow model I get the error message 
"Not enough memory to run on this device."

It seems the message is printed by https://github.com/pocl/pocl/blob/master/lib/CL/devices/common.c as this is the only Google result.

However when I evaluate the same model (i.e. same .pb file) in a minimal program it works. It only causes trouble when calling it in my bigger application.

My go runs in a VM with 8GB of RAM. Peak memory usage seems to be about 1,6 GB for the full application and 1,4GB for the demo.

I think I might be missing somehting obvious, but I cannot find it.

## Code

This is the example that works:

```go
package main

import (
        "bufio"
        "fmt"
        "image"
        "image/color"
        "io/ioutil"
        "os"
        "log"
        "path"

        "gocv.io/x/gocv"
)

func main() {
        if len(os.Args) < 4 {
                fmt.Println("How to run:\ntf-classifier [photo dir] [modelfile] [descriptionsfile]")
                return
        }

        // parse args
        photoDir := os.Args[1]
        model := os.Args[2]
        descr := os.Args[3]
        descriptions, err := readDescriptions(descr)
        if err != nil {
                fmt.Printf("Error reading descriptions file: %v\n", descr)
                return
        }
        fmt.Printf("%d descriptions read", len(descriptions))

        backend := gocv.NetBackendDefault
        if len(os.Args) > 4 {
                backend = gocv.ParseNetBackend(os.Args[4])
        }

        target := gocv.NetTargetCPU
        if len(os.Args) > 5 {
                target = gocv.ParseNetTarget(os.Args[5])
        }

        // open capture device
        //webcam, err := gocv.OpenVideoCapture(deviceID)
        //if err != nil {
        //      fmt.Printf("Error opening video capture device: %v\n", deviceID)
        //      return
        //}
        //defer webcam.Close()

        files, err := ioutil.ReadDir(photoDir)
        if err != nil {
                fmt.Println("Error reading photo directory.")
                log.Fatal(err)
        }

        window := gocv.NewWindow("Tensorflow Classifier")
        defer window.Close()

        img := gocv.NewMat()
        defer img.Close()

        // open DNN classifier
        net := gocv.ReadNet(model, "")
        if net.Empty() {
                fmt.Printf("Error reading network model : %v\n", model)
                return
        }
        defer net.Close()
        net.SetPreferableBackend(gocv.NetBackendType(backend))
        net.SetPreferableTarget(gocv.NetTargetType(target))

        status := "Ready"
        statusColor := color.RGBA{0, 255, 0, 0}
        fmt.Printf("Start classifying %d pictures.\n", len(files))

        for _,f := range files {
                //if ok := webcam.Read(&img); !ok {
                //      fmt.Printf("Device closed: %v\n", deviceID)
                //      return
                //}

                img := gocv.IMRead(path.Join(photoDir, f.Name()), gocv.IMReadColor)
                if img.Empty() {
                        fmt.Printf("Could not proces file %s \n", f.Name())
                        continue
                }

                // convert image Mat to 224x224 blob that the classifier can analyze
                blob := gocv.BlobFromImage(img, 1.0, image.Pt(224, 224), gocv.NewScalar(0, 0, 0, 0), true, false)

                // feed the blob into the classifier
                net.SetInput(blob, "input")

                // run a forward pass thru the network
                prob := net.Forward("vgg_19/fc8/squeezed")

                // reshape the results into a 1x1000 matrix
                probMat := prob.Reshape(1, 1)

                // determine the most probable classification
                _, maxVal, _, maxLoc := gocv.MinMaxLoc(probMat)

                indexMat := gocv.NewMat()

                gocv.SortIdx(probMat, &indexMat, gocv.SortDescending)

                fmt.Printf("Image: %s,\n", f.Name())

                k := 5
                // display classification
                desc := "Unknown"

                for i := 0; i < k; i++ {
                        index := int(indexMat.GetIntAt(0,i))
                        if index > len(descriptions) {
                                fmt.Println(index)
                                continue;
                        }
                        val := probMat.GetFloatAt(0, index)
                        desc := descriptions[index]
                        fmt.Printf("description: %v, val: %v\n", desc, val)
                }

                if maxLoc.X < 1000 {
                        desc = descriptions[maxLoc.X]
                }
                status = fmt.Sprintf("description: %v, maxVal: %v\n", desc, maxVal)
                gocv.PutText(&img, status, image.Pt(10, 20), gocv.FontHersheyPlain, 1.2, statusColor, 2)

                fmt.Printf("Best fit: \n%s\n", status)

                blob.Close()
                prob.Close()
                probMat.Close()

                window.IMShow(img)
                if window.WaitKey(1) >= 0 {
                        break
                }
        }
}

// readDescriptions reads the descriptions from a file
// and returns a slice of its lines.
func readDescriptions(path string) ([]string, error) {
        file, err := os.Open(path)
        if err != nil {
                return nil, err
        }
        defer file.Close()

        var lines []string
        scanner := bufio.NewScanner(file)
        for scanner.Scan() {
                lines = append(lines, scanner.Text())
        }
        return lines, scanner.Err()
}

```

These are the functions where I call the model in my application:

```go
func (gcvc *gocvTensorFlowClassifier) LoadFrozenModel(modelFile string) (err error) {
	filepath := gcvc.dataPathForResource(modelFile)
	gcvc.log.WithField("file", filepath).Infoln("loading frozen model")
	gcvc.net = gocv.ReadNetFromTensorflow(filepath)
        // also tried the following
	//gcvc.net = gocv.ReadNet(filepath, "")
	err = gcvc.net.SetPreferableBackend(gcvc.config.Backend)
	if err != nil {
		gcvc.log.WithError(err).Errorln("error when setting backend for tensorflow network")
		return err
	}
	err = gcvc.net.SetPreferableTarget(gcvc.config.Target)
	if err != nil {
		gcvc.log.WithError(err).Errorln("error when setting target for tensorflow network")
		return err
	}
	return nil
}

func (gcvc *gocvTensorFlowClassifier) ClassifyImages(image []image.Image) ([][]tag.Tag, error) {
	if gcvc.net.Empty() {
		return nil, errors.New("no gocv net loaded")
	}

	for _, curImage := range image {
		filename := curImage.GetFilename()

		// read image from file
		img := gocv.IMRead(filename, gocv.IMReadColor)

		// convert to a 224x244 image blob that can be processed by Tensorflow
		blob := gocv.BlobFromImage(img, 1.0, goimage.Pt(224, 244), gocv.NewScalar(0, 0, 0, 0), true, false)
		defer blob.Close()

		// feed the blob into the classifier
		gcvc.net.SetInput(blob, gcvc.config.InputTag)

		// run a forward pass thru the network
		prob := gcvc.net.Forward(gcvc.config.OutputTag)
		defer prob.Close()

		// reshape the results into a 1x1000 matrix
		probMat := prob.Reshape(1, 1)
		defer probMat.Close()

		// determine the most probable classification, and display it
		_, maxVal, _, maxLoc := gocv.MinMaxLoc(probMat)
		fmt.Printf("maxLoc: %v, maxVal: %v\n", maxLoc, maxVal)

		gocv.WaitKey(1)
	}

	return nil, nil
}
```
Full source code available at https://github.com/twatzl/imtag

## Your Environment

* Operating System and version: Fedora 64-bit with kernel 5.2.11-100.fc29.x86_64
* How did you install OpenCV? Don't know anymore, most likely manual build
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
no

```
$ go run ./cmd/version/main.go
gocv version: 0.20.0
opencv lib version: 4.1.0
```

```
$ go version
go version go1.12.7 linux/amd64
```

**Comment by twatzl** [comment]
Analysis with gdb

```
$ gdb main                                                                                                      
GNU gdb (GDB) Fedora 8.2-7.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from main...done.
warning: File "/usr/local/go/src/runtime/runtime-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py
line to your configuration file "/home/twatzl/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/twatzl/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
(gdb) run tag --rawClassification -f ./data/testdata/dog.jpg --config ./config.yaml --classifier="gocv_vgg" -k=20
Starting program: /home/twatzl/go/src/github.com/twatzl/imtag/main tag --rawClassification -f ./data/testdata/dog.jpg --config ./config.yaml --classifier="gocv_vgg" -k=20
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-39.fc29.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffe3d46700 (LWP 3979)]
[New Thread 0x7fffe3545700 (LWP 3980)]
[New Thread 0x7fffe2d44700 (LWP 3981)]
[New Thread 0x7fffe2543700 (LWP 3982)]
[New Thread 0x7fffe1d42700 (LWP 3983)]
[New Thread 0x7fffe1541700 (LWP 3984)]
Using config file: ./config.yaml
INFO[0002]/home/twatzl/go/tagger/imageClassifier/gocvTfClassifier/gocvtfclassifier.go:116 github.com/twatzl/imtag/tagger/imageClassifier/gocvTfClassifier.(*gocvTensorFlowClassifier).ClassifyImages() loading frozen model                          fields.file=data/tensorflowModels/frozen_vgg_19.pb file=data/tensorflowModels/frozen_vgg_19.pb
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffcbd6e700 (LWP 3985)]
[New Thread 0x7fffcb56d700 (LWP 3986)]
[New Thread 0x7fffcad6c700 (LWP 3987)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffb2728700 (LWP 3988)]
[New Thread 0x7fffb1f27700 (LWP 3989)]
[New Thread 0x7fffb1726700 (LWP 3990)]
[New Thread 0x7fffb0f25700 (LWP 3991)]
[Thread 0x7fffb0f25700 (LWP 3991) exited]
[Thread 0x7fffb1726700 (LWP 3990) exited]
[Thread 0x7fffb1f27700 (LWP 3989) exited]
[Thread 0x7fffb2728700 (LWP 3988) exited]
corrupted size vs. prev_size

Thread 5 "main" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe2543700 (LWP 3982)]
0x00007fffe902f57f in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install adwaita-gtk2-theme-3.28-2.fc29.x86_64 atk-2.30.0-1.fc29.x86_64 bzip2-libs-1.0.6-28.fc29.x86_64 cairo-1.16.0-3.fc29.x86_64 clang-libs-7.0.1-6.fc29.x86_64 elfutils-libelf-0.176-1.fc29.x86_64 expat-2.2.7-1.fc29.x86_64 freetype-2.9.1-6.fc29.x86_64 fribidi-1.0.5-1.fc29.x86_64 gdk-pixbuf2-2.38.1-1.fc29.x86_64 glib2-2.58.3-1.fc29.x86_64 graphite2-1.3.13-1.fc29.x86_64 gtk2-2.24.32-4.fc29.x86_64 harfbuzz-1.8.7-1.fc29.x86_64 hwloc-libs-1.11.12-1.fc29.x86_64 jbigkit-libs-2.1-15.fc29.x86_64 libX11-1.6.7-1.fc29.x86_64 libXau-1.0.8-14.fc29.x86_64 libXcomposite-0.4.4-15.fc29.x86_64 libXcursor-1.1.15-4.fc29.x86_64 libXdamage-1.1.4-15.fc29.x86_64 libXext-1.3.3-10.fc29.x86_64 libXfixes-5.0.3-8.fc29.x86_64 libXi-1.7.9-8.fc29.x86_64 libXinerama-1.1.4-2.fc29.x86_64 libXrandr-1.5.1-8.fc29.x86_64 libXrender-0.9.10-8.fc29.x86_64 libblkid-2.32.1-1.fc29.x86_64 libdatrie-0.2.9-8.fc29.x86_64 libdc1394-2.2.2-11.fc29.x86_64 libdrm-2.4.97-1.fc29.x86_64 libedit-3.1-24.20170329cvs.fc29.x86_64 libffi-3.1-18.fc29.x86_64 libgcc-8.3.1-2.fc29.x86_64 libjpeg-turbo-2.0.2-1.fc29.x86_64 libpng-1.6.34-7.fc29.x86_64 libraw1394-2.1.2-7.fc29.x86_64 libselinux-2.8-6.fc29.x86_64 libstdc++-8.3.1-2.fc29.x86_64 libthai-0.1.28-1.fc29.x86_64 libtool-ltdl-2.4.6-27.fc29.x86_64 libusbx-1.0.22-1.fc29.x86_64 libuuid-2.32.1-1.fc29.x86_64 libxcb-1.13.1-1.fc29.x86_64 llvm-libs-7.0.1-4.fc29.x86_64 mesa-dri-drivers-18.3.6-3.fc29.x86_64 ncurses-libs-6.1-8.20180923.fc29.x86_64 numactl-libs-2.0.12-1.fc29.x86_64 ocl-icd-2.2.12-2.fc29.x86_64 pango-1.42.4-3.fc29.x86_64 pcre-8.43-2.fc29.x86_64 pixman-0.34.0-10.fc29.x86_64 zlib-1.2.11-17.fc29.x86_64
(gdb) list
1       // Copyright © 2019 Tobias Watzl                                                                                                                                                                                                                           
2                                                                                                                                                                                                                                                                  
3       package main                                                                                                                                                                                                                                               
4                                                                                                                                                                                                                                                                  
5       import "github.com/twatzl/imtag/cmd"                                                                                                                                                                                                                       
6                                                                                                                                                                                                                                                                  
7       func main() {                                                                                                                                                                                                                                              
8               cmd.Execute()                                                                                                                                                                                                                                      
9       }                                                                                                                                                                                                                                                          
(gdb) bt                                                                                                                                                                                                                                                           
#0  0x00007fffe902f57f in raise () at /lib64/libc.so.6                                                                                                                                                                                                             
#1  0x00007fffe9019895 in abort () at /lib64/libc.so.6                                                                                                                                                                                                             
#2  0x00007fffe90729d7 in __libc_message () at /lib64/libc.so.6                                                                                                                                                                                                    
#3  0x00007fffe9079fac in  () at /lib64/libc.so.6                                                                                                                                                                                                                  
#4  0x00007fffe907d62c in _int_malloc () at /lib64/libc.so.6                                                                                                                                                                                                       
#5  0x00007fffe907e99a in malloc () at /lib64/libc.so.6                                                                                                                                                                                                            
#6  0x00007fffe7909f3a in hwloc_alloc_setup_object () at /usr/local/lib/libtensorflow_framework.so.1                                                                                                                                                               
#7  0x00007fffe79140c3 in look_sysfscpu () at /usr/local/lib/libtensorflow_framework.so.1                                                                                                                                                                          
#8  0x00007fffe7917372 in hwloc_look_linuxfs () at /usr/local/lib/libtensorflow_framework.so.1                                                                                                                                                                     
#9  0x00007fffe790cbd7 in hwloc_topology_load () at /usr/local/lib/libtensorflow_framework.so.1                                                                                                                                                                    
#10 0x00007fffca4b58ef in  () at /lib64/libpocl.so.2.2.0                                                                                                                                                                                                           
#11 0x00007fffca4b11ad in  () at /lib64/libpocl.so.2.2.0                                                                                                                                                                                                           
#12 0x00007fffca4abb51 in  () at /lib64/libpocl.so.2.2.0                                                                                                                                                                                                           
#13 0x00007fffca492e5b in  () at /lib64/libpocl.so.2.2.0                                                                                                                                                                                                           
#14 0x00007fffca534d0e in clGetDeviceIDs () at /lib64/libOpenCL.so.1                                                                                                                                                                                               
#15 0x00007fffca52be71 in _initClIcd_real () at /lib64/libOpenCL.so.1                                                                                                                                                                                              
#16 0x00007fffca52d35c in clGetPlatformIDs () at /lib64/libOpenCL.so.1                                                                                                                                                                                             
#17 0x00007ffff27a2486 in cv::ocl::haveOpenCL() () at /usr/local/lib64/libopencv_core.so.4.1
#18 0x00007ffff27a52f8 in cv::ocl::useOpenCL() () at /usr/local/lib64/libopencv_core.so.4.1
#19 0x00007ffff2800b79 in cv::UMat::getStdAllocator() () at /usr/local/lib64/libopencv_core.so.4.1
#20 0x00007ffff2801115 in cv::UMat::create(int, int const*, int, cv::UMatUsageFlags) () at /usr/local/lib64/libopencv_core.so.4.1
#21 0x00007ffff277061e in cv::_OutputArray::create(int, int const*, int, int, bool, cv::_OutputArray::DepthMask) const () at /usr/local/lib64/libopencv_core.so.4.1
#22 0x00007ffff269cbde in cv::Mat::copyTo(cv::_OutputArray const&) const () at /usr/local/lib64/libopencv_core.so.4.1
#23 0x00007ffff77d1d0e in cv::dnn::PermuteLayerImpl::finalize(cv::_InputArray const&, cv::_OutputArray const&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#24 0x00007ffff775ed24 in cv::dnn::dnn4_v20190122::Layer::finalize(std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#25 0x00007ffff7779bf8 in cv::dnn::dnn4_v20190122::Net::Impl::allocateLayer(int, std::map<int, cv::dnn::dnn4_v20190122::(anonymous namespace)::LayerShapes, std::less<int>, std::allocator<std::pair<int const, cv::dnn::dnn4_v20190122::(anonymous namespace)::LayerShapes> > > const&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#26 0x00007ffff777b0f0 in cv::dnn::dnn4_v20190122::Net::Impl::allocateLayers(std::vector<cv::dnn::dnn4_v20190122::LayerPin, std::allocator<cv::dnn::dnn4_v20190122::LayerPin> > const&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#27 0x00007ffff777b46d in cv::dnn::dnn4_v20190122::Net::Impl::setUpNet(std::vector<cv::dnn::dnn4_v20190122::LayerPin, std::allocator<cv::dnn::dnn4_v20190122::LayerPin> > const&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#28 0x00007ffff777bce5 in cv::dnn::dnn4_v20190122::Net::forward(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /usr/local/lib64/libopencv_dnn.so.4.1
#29 0x00000000008abcd8 in Net_Forward(Net, char const*) (net=0x7fffd8000d70, outputName=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:252
#30 0x00000000008a443b in _cgo_fc14ed73de64_Cfunc_Net_Forward (v=0xc000149868) at cgo-gcc-prolog:195
#31 0x0000000000476380 in runtime.asmcgocall () at /usr/local/go/src/runtime/asm_amd64.s:635
#32 0x0000000000473fd1 in runtime.exitsyscallfast.func1 () at /usr/local/go/src/runtime/proc.go:3041
#33 0x000000c000000180 in  ()
#34 0x000000000044f2a0 in runtime.mstart () at /usr/local/go/src/runtime/proc.go:1082
#35 0x000000c00007a180 in  ()
#36 0x0000000000800000 in github.com/pelletier/go-toml.(*tomlLexer).lexLiteralStringAsString (l=0x7fffe35445ff, terminator=..., discardLeadingNewLine=112, ~r2=..., ~r3=...) at /home/twatzl/go/src/github.com/pelletier/go-toml/lexer.go:381
#37 0x00007fffe35445fe in  ()
#38 0x00007fffe35445ff in  ()
#39 0x00007fffe35446e0 in  ()
#40 0x00007fffe2542b00 in  ()
#41 0x953be3dc69ac8470 in  ()
#42 0x953bf5ebf5be8470 in  ()
#43 0x0000000000000000 in  ()
(gdb) 
```

**Comment by twatzl** [comment]
Hello. Is there any further update on this or hint what could be wrong?
