### ISSUE TITLE
Runtime error using SURF

### ISSUE THREAD

**Issue by anysz** [hybridgroup/gocv#526]
## Description
I build OpenCV from the source, everything works fine except for the Contrib library

## Steps to Reproduce
1. Clone OpenCV and Contrib
2. Build and copy paste the library to MinGW env
3. No compile error, got runtime error

## Your Environment
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\home 3\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Go_files
set GOPROXY=
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\HOME3~1\AppData\Local\Temp\go-build584934418=/tmp/go-build -gno-record-gcc-switches

* Operating System and version: Windows 10
* OpenCV version used: 4.0.1
* How did you install OpenCV? Build them
* GoCV version used: 0.19.0
* Go version: go version go1.12.6 windows/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? it successfully compiled, just got runtime error for usng Contrib library

**Comment by anysz** [comment]
```$ cv_ver
Exception 0x20474343 0x3751390 0x0 0x7ffe9dd8a1c8
PC=0x7ffe9dd8a1c8

runtime: unknown pc 0x7ffe9dd8a1c8
stack: frame={sp:0x24f9a0, fp:0x0} stack=[0x0,0x24fdf0)
000000000024f8a0:  0000000000020310  0000000000022b52
000000000024f8b0:  0000000000000000  00000000000233bc
000000000024f8c0:  000000000002ad50  0000000000000002
000000000024f8d0:  0000000000000000  0000000000000010
000000000024f8e0:  0000000000000002  0000000000000000
000000000024f8f0:  0000000000000001  0000000000000001
000000000024f900:  0000000000020000  00007ffea08aef52
000000000024f910:  0000000000020000  0000000000000002
000000000024f920:  00000000002a0000  0000000000000020
000000000024f930:  0000000000020310  000000000024f9a8
000000000024f940:  00000000002a0cc0  0000000000000020
000000000024f950:  000000000000001c  00000000037515c0
000000000024f960:  0000bb6653f012f5  0000000000000000
000000000024f970:  0000000000000000  0000000000000000
000000000024f980:  00000000005139ca  0000000003751430
000000000024f990:  0000000003751410  00007ffe9dd8a1c8
000000000024f9a0: <0000000000020000  0000000003751390
000000000024f9b0:  00000000650282c0  00000000651aa3d0
000000000024f9c0:  0000000020474343  0000000000000000
000000000024f9d0:  00007ffe9dd8a1c8  0000000000000001
000000000024f9e0:  0000000003751390  0000000000000000
000000000024f9f0:  0000000000000000  0000000000000000
000000000024fa00:  00000000005139ca  0000000003751430
000000000024fa10:  0000000000000018  0000000000000008
000000000024fa20:  0000000000000010  00007ffe9e419c30
000000000024fa30:  0000000000000021  0000000000000018
000000000024fa40:  00000000005139ca  0000000000000002
000000000024fa50:  000000006fd0e540  000000006144db3d
000000000024fa60:  0000a3236e9ccd44  0000000000000008
000000000024fa70:  0000000000000000  000000006144d191
000000000024fa80:  00000000037513d0  00000000650282c0
000000000024fa90:  00000000651aa3d0  0000000003751410
runtime: unknown pc 0x7ffe9dd8a1c8
stack: frame={sp:0x24f9a0, fp:0x0} stack=[0x0,0x24fdf0)
000000000024f8a0:  0000000000020310  0000000000022b52
000000000024f8b0:  0000000000000000  00000000000233bc
000000000024f8c0:  000000000002ad50  0000000000000002
000000000024f8d0:  0000000000000000  0000000000000010
000000000024f8e0:  0000000000000002  0000000000000000
000000000024f8f0:  0000000000000001  0000000000000001
000000000024f900:  0000000000020000  00007ffea08aef52
000000000024f910:  0000000000020000  0000000000000002
000000000024f920:  00000000002a0000  0000000000000020
000000000024f930:  0000000000020310  000000000024f9a8
000000000024f940:  00000000002a0cc0  0000000000000020
000000000024f950:  000000000000001c  00000000037515c0
000000000024f960:  0000bb6653f012f5  0000000000000000
000000000024f970:  0000000000000000  0000000000000000
000000000024f980:  00000000005139ca  0000000003751430
000000000024f990:  0000000003751410  00007ffe9dd8a1c8
000000000024f9a0: <0000000000020000  0000000003751390
000000000024f9b0:  00000000650282c0  00000000651aa3d0
000000000024f9c0:  0000000020474343  0000000000000000
000000000024f9d0:  00007ffe9dd8a1c8  0000000000000001
000000000024f9e0:  0000000003751390  0000000000000000
000000000024f9f0:  0000000000000000  0000000000000000
000000000024fa00:  00000000005139ca  0000000003751430
000000000024fa10:  0000000000000018  0000000000000008
000000000024fa20:  0000000000000010  00007ffe9e419c30
000000000024fa30:  0000000000000021  0000000000000018
000000000024fa40:  00000000005139ca  0000000000000002
000000000024fa50:  000000006fd0e540  000000006144db3d
000000000024fa60:  0000a3236e9ccd44  0000000000000008
000000000024fa70:  0000000000000000  000000006144d191
000000000024fa80:  00000000037513d0  00000000650282c0
000000000024fa90:  00000000651aa3d0  0000000003751410

goroutine 1 [syscall]:
gocv.io/x/gocv/contrib._Cfunc_SURF_Create(0x0)
        _cgo_gotypes.go:375 +0x51
gocv.io/x/gocv/contrib.NewSURF(...)
        D:/Go_files/src/gocv.io/x/gocv/contrib/xfeatures2d.go:78
main.main()
        D:/LINE/_prj_shared/MyGolang/ImageServer/cv_ver.go:11 +0x84
rax     0x1ff
rbx     0x3751390
rcx     0x36bfe90
rdi     0x651aa3d0
rsi     0x650282c0
rbp     0x3751410
rsp     0x24f9a0
r8      0x6572616800000001
r9      0x36a4670
r10     0x0
r11     0x635f766301650004
r12     0x3751430
r13     0x5139ca
r14     0x0
r15     0x0
rip     0x7ffe9dd8a1c8
rflags  0x206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by anysz** [comment]
![image](https://user-images.githubusercontent.com/26342994/67148815-04400500-f2ce-11e9-8396-bfb3fc926e14.png)

**Comment by anysz** [comment]
Everything else works just fine
![image](https://user-images.githubusercontent.com/26342994/67148827-3b161b00-f2ce-11e9-956e-61add94d3a74.png)

**Comment by deadprogram** [comment]
Hello @anysz are you certain that you compiled `contrib` with OpenCV when you built it? You would need some flags like these in your build command for OpenCV:

```shell
-DOPENCV_EXTRA_MODULES_PATH=C:\opencv\opencv_contrib-4.1.2\modules -DBUILD_SHARED_LIBS=ON
```

That is from https://github.com/hybridgroup/gocv/blob/master/win_build_opencv.cmd#L35

**Comment by deadprogram** [comment]
I'd suggest update to the latest OpenCV (4.1.2) and latest GoCV (0.21.0) to make sure that the versions are in sync.

On the Windows CI server the test passes:
https://ci.appveyor.com/project/deadprogram/gocv/branch/dev#L649

This would seem to indicate something related to your version or environment.

**Comment by deadprogram** [comment]
Any other info on this issue @anysz or should we close it?

**Comment by thanatos915** [comment]
@deadprogram I have the same problem with win10. Whether to rely on other lib
