### ISSUE TITLE
SetUCharAt3 segmentation violation

### ISSUE THREAD

**Issue by rodneymo** [hybridgroup/gocv#590]
When trying to set color value using SetUCharAt3 on channel 2 pixels a segmentation violation occurs. This happens irrespective of the method used to create the destination Mat (in my example below b). If instead of creating a MAT clone or copy I modify the original Mat (a) then it works fine.
Might be related to #583 

`
func main() {
	a := gocv.IMRead("image.jpg", gocv.IMReadAnyColor)
	defer a.Close()
	colorType := a.Type()
	fmt.Println("color type for image: " + colorType.String())

	fmt.Println("rows: " + strconv.Itoa(a.Rows()))
	fmt.Println("columns: " + strconv.Itoa(a.Cols()))

	fmt.Printf("number of channels in image %v\n", a.Channels())
	b := a.Clone()
	defer b.Close()
	fmt.Println("color type for image: " + b.Type().String())

	fmt.Println("rows: " + strconv.Itoa(b.Rows()))
	fmt.Println("columns: " + strconv.Itoa(b.Cols()))

	for i := 0; i < a.Rows(); i++ {
		for j := 0; j < a.Cols(); j++ {
			for channel := 0; channel < 3; channel++ {
				color := a.GetUCharAt3(i, j, channel)
				// fmt.Printf("%d,%d\n", i, j)
				color -= 2
				// color *= 10
				b.SetUCharAt3(i, j, channel, color)
			}
		}
	}
	w := gocv.NewWindow("hello")
	defer w.Close()
	w2 := gocv.NewWindow("hello2")
	defer w2.Close()
	w.IMShow(a)
	w2.IMShow(b)
	for {
		if w.WaitKey(0) == 13 || w2.WaitKey(0) == 13 {
			fmt.Println("return key pressed")
			break
		}

	}
}

`

Here's the error:

> color type for image: CV8UC3
rows: 200
columns: 300
number of channels in image 3
color type for image: CV8UC3
rows: 200
columns: 300
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7faf69439670 pc=0x4b3f98]

runtime stack:
runtime.throw(0x504171, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0x4aefa0, 0xc000044cb0, 0x0)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000044c80 sp=0xc000044c48 pc=0x41cb6b
gocv.io/x/gocv._Cfunc_Mat_SetUChar3(0x1f41290, 0x0, 0x2900000001)
        _cgo_gotypes.go:4166 +0x45 fp=0xc000044cb0 sp=0xc000044c80 pc=0x4abd65
gocv.io/x/gocv.(*Mat).SetUCharAt3.func1(0xc000044ec0, 0x0, 0x0, 0x1, 0x129)
        /home/ramf/dev/go/src/gocv.io/x/gocv/core.go:620 +0x82 fp=0xc000044cf0 sp=0xc000044cb0 pc=0x4acc32
gocv.io/x/gocv.(*Mat).SetUCharAt3(0xc000044ec0, 0x0, 0x0, 0x1, 0x29)
        /home/ramf/dev/go/src/gocv.io/x/gocv/core.go:620 +0x52 fp=0xc000044d28 sp=0xc000044cf0 pc=0x4ac442
main.main()
        /home/ramf/dev/go/src/opencv/color_reduction/main.go:41 +0x705 fp=0xc000044f60 sp=0xc000044d28 pc=0x4ada15
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc000044fe0 sp=0xc000044f60 pc=0x44563e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x46dcc1
exit status 2

## Your Environment

* Operating System and version: ubuntu 18.04
* OpenCV version used: 4.20
* How did you install OpenCV?
* GoCV version used: 0.22.0
* Go version: 1.13.5
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? yes

**Comment by rodneymo** [comment]
So if I modify the original Mat (a) instead of the copy/clone (b) then it works. So it seems the problem is in the Mat copy/clone. Any ideas?

**Comment by twatzl** [comment]
Hey. OP from #583 here. I would just recommend using the SetUCharAt function and calculating the indices manually.
SetUCharAt3 is not intended for channel wise access at the moment from what I could see in the code.

**Comment by sean2077** [comment]
@rodneymo have you try to change 
```go
b.SetUCharAt3(i, j, channel, color)
```
to
```go
b.SetUCharAt3(j, i, channel, color)
```
?
