### ISSUE TITLE
NCS2/OpenVINO failure, unknown device GPU?

### ISSUE THREAD

**Issue by cameron5906** [hybridgroup/gocv#618]
I am trying to utilize my Intel Neural Compute Stick V2 with my program written with GoCV. I am able to run the samples provided by Intel so I know the model is working and the stick works, but for some reason I am getting this when attempting to run my program:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.2-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Device with "GPU" name is not registered in the InferenceEngine in function 'initPlugin'

SIGABRT: abort
PC=0x7627bf24 m=7 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0x7627bf24
stack: frame={sp:0x613fde40, fp:0x0} stack=[0x60bfefa4,0x613feba4)
613fddc0:  7656e93c  00000000  613fde0c  76f94968
613fddd0:  00000000  60a16e98  60a16eb0  764c18fc
613fdde0:  60a16e18  763657c0  60a16e18  764c18b2
613fddf0:  00000000  613fe02c  60a16e98  60a16e18
613fde00:  613fe02c  00000000  613fe02c  60a16e98
613fde10:  60a16eb0  613fe078  764c18b4  764c18fc
613fde20:  60a16e18  00000006  60a16ee0  60a16e7c
613fde30:  60a16e98  613fdec4  76f94968  7627bea8
613fde40: <60a16df8  00000000  00000000  60a64308
613fde50:  60a16e7c  60a16e98  60a16eb0  768d7348
613fde60:  60a96454  60a16e18  613fe078  764c18b4
613fde70:  764c18b4  613fe050  0000004e  60a16e98
613fde80:  60a16eb0  76f79b44  76ec2704  76568ccc
613fde90:  76ec2704  764c279c  76ec2704  764cb674
613fdea0:  00221334  76ec2704  76ec2713  00000011
613fdeb0:  76ec2713  613fdcc0  00000003  0000001e
runtime: unknown pc 0x7627bf24
stack: frame={sp:0x613fde40, fp:0x0} stack=[0x60bfefa4,0x613feba4)
613fddc0:  7656e93c  00000000  613fde0c  76f94968
613fddd0:  00000000  60a16e98  60a16eb0  764c18fc
613fdde0:  60a16e18  763657c0  60a16e18  764c18b2
613fddf0:  00000000  613fe02c  60a16e98  60a16e18
613fde00:  613fe02c  00000000  613fe02c  60a16e98
613fde10:  60a16eb0  613fe078  764c18b4  764c18fc
613fde20:  60a16e18  00000006  60a16ee0  60a16e7c
613fde30:  60a16e98  613fdec4  76f94968  7627bea8
613fde40: <60a16df8  00000000  00000000  60a64308
613fde50:  60a16e7c  60a16e98  60a16eb0  768d7348
613fde60:  60a96454  60a16e18  613fe078  764c18b4
613fde70:  764c18b4  613fe050  0000004e  60a16e98
613fde80:  60a16eb0  76f79b44  76ec2704  76568ccc
613fde90:  76ec2704  764c279c  76ec2704  764cb674
613fdea0:  00221334  76ec2704  76ec2713  00000011
613fdeb0:  76ec2713  613fdcc0  00000003  0000001e

goroutine 5 [syscall]:
runtime.cgocall(0x2212e8, 0x24346d8, 0x24346dc)
        /usr/lib/go-1.11/src/runtime/cgocall.go:128 +0x5c fp=0x24346c0 sp=0x24346a8 pc=0x3cb54
gocv.io/x/gocv._Cfunc_Net_Forward(0x63000690, 0x60a13fa8, 0x0)
        _cgo_gotypes.go:4713 +0x38 fp=0x24346d4 sp=0x24346c0 pc=0x2173d0
gocv.io/x/gocv.(*Net).Forward.func2(0x63000690, 0x60a13fa8, 0x60a13fa8)
        /home/pi/go/pkg/mod/gocv.io/x/gocv@v0.22.0/dnn.go:151 +0x4c fp=0x24346ec sp=0x24346d4 pc=0x218bc0
gocv.io/x/gocv.(*Net).Forward(0x2434790, 0x2b625c, 0xd, 0x0)
        /home/pi/go/pkg/mod/gocv.io/x/gocv@v0.22.0/dnn.go:151 +0x68 fp=0x2434700 sp=0x24346ec pc=0x217f14
main.Detect()
        /home/pi/overkill-ai/tracker.go:88 +0x2d4 fp=0x24347ec sp=0x2434700 pc=0x21a3b8
runtime.goexit()
        /usr/lib/go-1.11/src/runtime/asm_arm.s:867 +0x4 fp=0x24347ec sp=0x24347ec pc=0x8f908
created by main.TrackAndFollow
        /home/pi/overkill-ai/tracker.go:37 +0x38

goroutine 1 [sleep]:
time.Sleep(0x3b9aca00, 0x0)
        /usr/lib/go-1.11/src/runtime/time.go:105 +0x14c
main.main()
        /home/pi/overkill-ai/main.go:29 +0x1a8

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
        /usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
        /usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x30

goroutine 4 [running]:
        goroutine running on other thread; stack unavailable
created by main.TrackAndFollow
        /home/pi/overkill-ai/tracker.go:36 +0x24

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x613fde44
r2      0x0
r3      0x8
r4      0x76f94968
r5      0x6
r6      0x613fde44
r7      0xaf
r8      0x60a16e98
r9      0x60a16eb0
r10     0x768d7348
fp      0x60a96454
ip      0x0
sp      0x613fde40
lr      0xffffffff
pc      0x7627bf24
cpsr    0x10
fault   0x0
```

## Relevant code
```
protoFile := "/home/pi/neural/peds.bin"
modelFile := "/home/pi/neural/peds.xml"

net := gocv.ReadNet(modelFile, protoFile)
if net.Empty() {
	fmt.Println("Could not read network model")
	return
}
defer net.Close()
net.SetPreferableBackend(gocv.NetBackendOpenVINO)
net.SetPreferableTarget(gocv.NetTargetFP16)

blob := gocv.BlobFromImage(img, 1.0, image.Pt(672, 384), gocv.NewScalar(104.0, 177.0, 123.0, 0), true, false)
defer blob.Close()

net.SetInput(blob, "data")

detBlob := net.Forward("detection_out")
defer detBlob.Close()
```

## Environment
* Operating System and version: 
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
* OpenCV version used: 
4.1.2-openvino
* How did you install OpenCV?
Using the Intel documentation and the openVINO toolkit
* GoCV version used:
0.22.0
* Go version:
go1.11.6 linux/arm
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
Yes

**Comment by Danile71** [comment]
NetTargetFP16 - intel gpu
NetTargetVPU - stick
