### ISSUE TITLE
MacOS High Sierra 10.13.2 error while face detection 

### ISSUE THREAD

**Issue by 0just0** [hybridgroup/gocv#68]
I have installed the library and run a couple of examples successfully but got this error message while running face detection code from documentation

```start reading camera device: 0
OpenCV Error: Assertion failed (!empty()) in detectMultiScale, file /tmp/opencv-20180113-80339-d8g5mw/opencv-3.4.0/modules/objdetect/src/cascadedetect.cpp, line 1698
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20180113-80339-d8g5mw/opencv-3.4.0/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215) !empty() in function detectMultiScale

SIGABRT: abort
PC=0x7fff6dbc6e3e m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x409ef30, 0xc420057dd0, 0xc420057df8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/cgocall.go:132 +0xe4 fp=0xc420057da0 sp=0xc420057d60 pc=0x40041a4
gocv.io/x/gocv._Cfunc_CascadeClassifier_DetectMultiScale(0xb112c10, 0xb135390, 0x0, 0x0)
	gocv.io/x/gocv/_obj/_cgo_gotypes.go:644 +0x57 fp=0xc420057dd0 sp=0xc420057da0 pc=0x409a9e7
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale.func1(0xb112c10, 0xb135390, 0x0, 0x0)
	/Users/Dmitry/go/src/gocv.io/x/gocv/objdetect.go:53 +0xb5 fp=0xc420057e18 sp=0xc420057dd0 pc=0x409c5f5
gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale(0xc420057f20, 0xb135390, 0x0, 0x0, 0x0)
	/Users/Dmitry/go/src/gocv.io/x/gocv/objdetect.go:53 +0x63 fp=0xc420057e90 sp=0xc420057e18 pc=0x409bcc3
main.main()
	/Users/Dmitry/go/src/github.com/0just0/test_cv/cv.go:49 +0x24b fp=0xc420057f80 sp=0xc420057e90 pc=0x409cd8b
runtime.main()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195 +0x226 fp=0xc420057fe0 sp=0xc420057f80 pc=0x402b7f6
runtime.goexit()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420057fe8 sp=0xc420057fe0 pc=0x4053641

rax    0x0
rbx    0x7fffa6add340
rcx    0x7ffeefbfdc58
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfdc90
rsp    0x7ffeefbfdc58
r8     0x7ffeefbfdb20
r9     0x0
r10    0x0
r11    0x206
r12    0x307
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff6dbc6e3e
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by 0just0** [comment]
Ok, it appears, that you need to have `haarcascade_frontalface_default.xml` in your folder while using it. I thought that library will somehow find the file itself in the src folder.
