### ISSUE TITLE
Mean subtraction is not supported for CV_8U blob depth" in function 'blobFromImages

### ISSUE THREAD

**Issue by wlwatkins** [hybridgroup/gocv#699]
Error running default caffe-classifier, the message reads:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0) /tmp/opencv/opencv-4.3.0/modules/dnn/src/dnn.cpp:334: error: (-215:Assertion failed) mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth" in function 'blobFromImages'

```

## Description
Immediate crash when running any example that uses `blobFromImages`, for example:
https://github.com/hybridgroup/gocv/blob/master/cmd/caffe-classifier/main.go

The simple facedetect example from https://github.com/hybridgroup/gocv/blob/master/cmd/facedetect/main.go works fine

## Steps to Reproduce
Copied the example on a raspberry pi, and run as is

## Your Environment

* Operating System and version:
```
$ uname -a
Linux amos 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```
* OpenCV version used: 
```
$ go run ./cmd/version/main.go
gocv version: 0.23.0
opencv lib version: 4.3.0
```
* How did you install OpenCV?
Through the quick install in https://gocv.io/getting-started/linux/
* GoCV version used:
```
$ go run ./cmd/version/main.go
gocv version: 0.23.0
opencv lib version: 4.3.0
```
* Go version:
```
$ go version
go version go1.14.4 linux/arm

```
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? 
no

## Full output
I've edited the code so to hard code the differnet files that are meant to be passed as arguments in the example
```
$ go run caffe.go
Start reading device: 0
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0) /tmp/opencv/opencv-4.3.0/modules/dnn/src/dnn.cpp:334: error: (-215:Assertion failed) mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth" in function 'blobFromImages'

SIGABRT: abort
PC=0xb4ba8f24 m=0 sigcode=4294967290
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xc3fc8, 0x82a55c, 0xc)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5c fp=0x82a520 sp=0x82a508 pc=0x2a8d8
gocv.io/x/gocv._Cfunc_Net_BlobFromImage(0x5c60f8, 0x0, 0x3ff00000, 0xe0, 0xe0, 0x0, 0x405a0000, 0x0, 0x405d4000, 0x0, ...)
        _cgo_gotypes.go:4761 +0x38 fp=0x82a558 sp=0x82a520 pc=0xbb560
gocv.io/x/gocv.BlobFromImage.func1(0x5c60f8, 0x0, 0x3ff00000, 0xe0, 0xe0, 0x0, 0x405a0000, 0x0, 0x405d4000, 0x0, ...)
        /home/pi/go/src/gocv.io/x/gocv/dnn.go:317 +0x80 fp=0x82a5b8 sp=0x82a558 pc=0xbd750
gocv.io/x/gocv.BlobFromImage(0x5c60f8, 0x0, 0x3ff00000, 0xe0, 0xe0, 0x0, 0x405a0000, 0x0, 0x405d4000, 0x0, ...)
        /home/pi/go/src/gocv.io/x/gocv/dnn.go:317 +0x7c fp=0x82a618 sp=0x82a5b8 pc=0xbc6a0
main.main()
        /home/pi/dev/drafts/caffe.go:78 +0x2c4 fp=0x82a7b8 sp=0x82a618 pc=0xbe310
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x208 fp=0x82a7e4 sp=0x82a7b8 pc=0x59e9c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:857 +0x4 fp=0x82a7e4 sp=0x82a7e4 pc=0x83cbc

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0xbeb9ec9c
r2      0x0
r3      0x8
r4      0xb6fec968
r5      0x6
r6      0xbeb9ec9c
r7      0xaf
r8      0x5b06e4
r9      0x5b0700
r10     0x5b0718
fp      0x5de358
ip      0x0
sp      0xbeb9ec98
lr      0xffffffff
pc      0xb4ba8f24
cpsr    0x10
fault   0x0
exit status 2

```

**Comment by wlwatkins** [comment]
is anyone incountering this issue as well? I mean could someone do the test and tell me if the same issue arises please?

**Comment by wlwatkins** [comment]
repost https://github.com/hybridgroup/gocv/issues/658
