### ISSUE TITLE
gocv.AccumulatedWeighted crashed program

### ISSUE THREAD

**Issue by Chipsterjulien** [hybridgroup/gocv#798]
Hi !

I have an issue with gocv.AccumulatedWeighted
```go
package main

import (
	"fmt"
	"os"

	"gocv.io/x/gocv"
)

func main() {
	startApp()
}

func startApp() {
	cap, err := gocv.VideoCaptureFile("http://192.168.1.2:8080/?action=stream")
	if err != nil {
		panic(err)
	}
	defer cap.Close()

	window := gocv.NewWindow("Motion Window")
	defer window.Close()
	frame := gocv.NewMat()
	defer frame.Close()
	gray := gocv.NewMat()
	defer gray.Close()
	avg := gocv.NewMat()
	defer avg.Close()

	for {
		if ok := cap.Read(&frame); !ok {
			fmt.Printf("Cannot read device")
			os.Exit(1)
		}
		if frame.Empty() {
			continue
		}

		gocv.CvtColor(frame, &gray, gocv.ColorBGRToGray)

		if avg.Empty() {
			gray.CopyTo(&avg)
			continue
		}

		gocv.AccumulatedWeighted(gray, &avg, 0.5)

		window.IMShow(gray)
		window.WaitKey(1)
	}
}
```

The error is:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1) /build/opencv/src/opencv-4.5.1/modules/imgproc/src/accum.cpp:619: error: (-215:Assertion failed) _src.sameSize(_dst) && dcn == scn in function 'accumulateWeighted'

SIGABRT: abort
PC=0x7fe6af809615 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x648c10, 0xc0001a1d78, 0xc000000000)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0001a1d48 sp=0xc0001a1d10 pc=0x42297b
gocv.io/x/gocv._Cfunc_Mat_AccumulatedWeighted(0x212ca50, 0x207b4f0, 0x3fe0000000000000)
        _cgo_gotypes.go:2932 +0x45 fp=0xc0001a1d78 sp=0xc0001a1d48 pc=0x6422e5
gocv.io/x/gocv.AccumulatedWeighted.func1(0x212ca50, 0x0, 0x0, 0x0, 0xc0001a1e98, 0x3fe0000000000000)
        /home/julien/.golang/src/gocv.io/x/gocv/imgproc.go:2159 +0x96 fp=0xc0001a1db0 sp=0xc0001a1d78 pc=0x643796
gocv.io/x/gocv.AccumulatedWeighted(0x212ca50, 0x0, 0x0, 0x0, 0xc0001a1e98, 0x3fe0000000000000)
        /home/julien/.golang/src/gocv.io/x/gocv/imgproc.go:2159 +0x5f fp=0xc0001a1df0 sp=0xc0001a1db0 pc=0x642edf
main.startApp()
        /home/julien/Programmation/Golang/0 - surveillance/surveillance.go:65 +0x297 fp=0xc0001a1f18 sp=0xc0001a1df0 pc=0x644e57
main.main()
        /home/julien/Programmation/Golang/0 - surveillance/surveillance.go:25 +0xb3 fp=0xc0001a1f88 sp=0xc0001a1f18 pc=0x644b73
runtime.main()
        /usr/lib/go/src/runtime/proc.go:204 +0x209 fp=0xc0001a1fe0 sp=0xc0001a1f88 pc=0x456c89
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0001a1fe8 sp=0xc0001a1fe0 pc=0x4880a1

rax    0x0
rbx    0x7fe6a277d1c0
rcx    0x7fe6af809615
rdx    0x0
rdi    0x2
rsi    0x7ffe5879c0b0
rbp    0x20f62f0
rsp    0x7ffe5879c0b0
r8     0x0
r9     0x7ffe5879c0b0
r10    0x8
r11    0x246
r12    0x1eccdb0
r13    0x7fe6affb7330
r14    0x1d59a10
r15    0x7ffe5879c3a0
rip    0x7fe6af809615
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by golubaca** [comment]
Based on this [question](https://answers.opencv.org/question/63781/accumulateweighted-problems/?sort=votes), if you change mat type, it will work
`gray.ConvertTo(&gray, gocv.MatTypeCV32FC1)`
Same issues appeared in this issue as well, and the solution is the same.

**Comment by Chipsterjulien** [comment]
I don't understand how use
```golang
gray.ConvertTo(&gray, gocv.MatTypeCV32FC1)
```
since everything i have tried is not working

**Comment by golubaca** [comment]
Like this:
```golang
package main

import (
	"fmt"
	"os"

	"gocv.io/x/gocv"
)

func main() {
	startApp()
}

func startApp() {
	cap, err := gocv.VideoCaptureFile("http://192.168.1.2:8080/?action=stream")
	if err != nil {
		panic(err)
	}
	defer cap.Close()

	window := gocv.NewWindow("Motion Window")
	defer window.Close()
	frame := gocv.NewMat()
	defer frame.Close()
	gray := gocv.NewMat()
	defer gray.Close()
	avg := gocv.NewMat()
	defer avg.Close()

	for {
		if ok := cap.Read(&frame); !ok {
			fmt.Printf("Cannot read device")
			os.Exit(1)
		}
		if frame.Empty() {
			continue
		}
		gray.Close()
		gray = gocv.NewMat()

		gocv.CvtColor(frame, &gray, gocv.ColorBGRToGray)
		gray.ConvertTo(&gray, gocv.MatTypeCV32FC1)

		if avg.Empty() {
			gray.CopyTo(&avg)
			// continue
		}
		gocv.AccumulatedWeighted(gray, &avg, 0.5)

		window.IMShow(gray)
		window.WaitKey(1)
	}
}
```

**Comment by Chipsterjulien** [comment]
Thx for you response.

I have tried this code before but always get a completely blank image. The same code in python works except unfortunately python is too slow to do what I want
