### ISSUE TITLE
install gocv successfully, but excute cmd/hello/main.go failed

### ISSUE THREAD

**Issue by Bevisy** [hybridgroup/gocv#903]
## Description

installed gocv successfully, and excute `go run ./cmd/hello/main.go`, but get error below
```sh
$ go run ./cmd/hello/main.go  
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.3) /tmp/opencv/opencv-4.5.3/modules/highgui/src/window.cpp:1257: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

SIGABRT: abort
PC=0x7f88770c918b m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4a22d0, 0xc000052ed8)
	/opt/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000052eb0 sp=0xc000052e78 pc=0x41e29c
gocv.io/x/gocv._Cfunc_Window_New(0xccd7d0, 0x0)
	_cgo_gotypes.go:7552 +0x45 fp=0xc000052ed8 sp=0xc000052eb0 pc=0x49dc25
gocv.io/x/gocv.NewWindow({0x4d5461, 0x5})
	/home/zbb/go/src/github.com/hybridgroup/gocv/highgui.go:39 +0x7e fp=0xc000052f18 sp=0xc000052ed8 pc=0x49defe
main.main()
	/home/zbb/go/src/github.com/hybridgroup/gocv/cmd/hello/main.go:9 +0x45 fp=0xc000052f80 sp=0xc000052f18 pc=0x49eb45
runtime.main()
	/opt/go/src/runtime/proc.go:255 +0x227 fp=0xc000052fe0 sp=0xc000052f80 pc=0x44dd87
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x4767a1

```
And I can confirm the `libgtk2.0-dev and pkg-config` is already existed.

## Steps to Reproduce

1. cd {gocv_repo} && make install
2. go run ./cmd/hello/main.go

## Your Environment

* Operating System and version: ubuntu 20.04; 5.11.0-36-generic
* OpenCV version used: 4.5.3
* How did you install OpenCV?: using quick install `make install`
* GoCV version used: 0.28.0
* Go version: go1.17

**Comment by Bevisy** [comment]
reinstall gocv and working well. Close this issue.
