### ISSUE TITLE
SIGSEGV: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by danhab99** [hybridgroup/gocv#981]
## Description

```go
groups := [][]image.Point{};
paths := make([]*gocv.PointsVector, len(groups))

for i, pixelGroup := range groups { //
   canvas := gocv.NewMatWithSize(width, height, gocv.MatTypeCV8U)
   defer canvas.Close()
   for _, pixel := range pixelGroup {
      canvas.SetIntAt(pixel.X, pixel.Y, 1)
   }

   path := gocv.FindContours(canvas, gocv.RetrievalTree, gocv.ChainApproxSimple)
   paths[i] = &path
}
```

Results in

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100000008 pc=0x7fb63eea7d05]

runtime stack:
runtime.throw({0x51cd29?, 0x7fb5fe2602c0?})
	/usr/lib/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall]:
runtime.cgocall(0x4d9450, 0xc0000b5a10)
	/usr/lib/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000b59e8 sp=0xc0000b59b0 pc=0x41fa1c
gocv.io/x/gocv._Cfunc_Mat_Close(0x7fb55e7e1840)
	_cgo_gotypes.go:3648 +0x45 fp=0xc0000b5a10 sp=0xc0000b59e8 pc=0x4d0fa5
gocv.io/x/gocv.(*Mat).Close.func1(0xc0000b5a70?)
	/home/dan/go/pkg/mod/gocv.io/x/gocv@v0.30.0/mat_noprofile.go:23 +0x3a fp=0xc0000b5a48 sp=0xc0000b5a10 pc=0x4d2d1a
gocv.io/x/gocv.(*Mat).Close(0xc00052b780)
	/home/dan/go/pkg/mod/gocv.io/x/gocv@v0.30.0/mat_noprofile.go:23 +0x1e fp=0xc0000b5a60 sp=0xc0000b5a48 pc=0x4d2c5e
demo.go/lib.RasterToVector.func4()
	/home/dan/go/src/detection-test/lib/raster_to_vector.go:137 +0x1d fp=0xc0000b5ab8 sp=0xc0000b5a60 pc=0x4d369d
runtime.deferreturn()
	/usr/lib/go/src/runtime/panic.go:436 +0x33 fp=0xc0000b5af8 sp=0xc0000b5ab8 pc=0x44cdb3
demo.go/lib.RasterToVector(0xc00013c040)
	/home/dan/go/src/detection-test/lib/raster_to_vector.go:152 +0x418 fp=0xc0000b5cc0 sp=0xc0000b5af8 pc=0x4d31f8
main.main()
	/home/dan/go/src/detection-test/demo.go:68 +0x86a fp=0xc0000b5f80 sp=0xc0000b5cc0 pc=0x4d42ea
runtime.main()
	/usr/lib/go/src/runtime/proc.go:250 +0x212 fp=0xc0000b5fe0 sp=0xc0000b5f80 pc=0x450812
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x47b1a1
exit status 2
```

## Steps to Reproduce

1. In a loop, copy array of `image.Point`s to gocv matrix
2. Apply FindContours function
3. Add to slice
4. Return slice

## Your Environment

* Operating System and version:
* OpenCV version used: 5.10.109-1-MANJARO
* How did you install OpenCV? `go get gocv.io/x/gocv`
* GoCV version used: v0.30.0
* Go version: `go version go1.18.1 linux/amd64`
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? Script says I don't need to run it ¯\\\_(ツ)_/¯

**Comment by berak** [comment]
`canvas := gocv.NewMatWithSize(width, height, gocv.MatTypeCV8U)`

please swap width and height, see:

https://github.com/hybridgroup/gocv/blob/17b43c201f8d8f9268c89ae138aa9b7174411caa/core.go#L196

**Comment by danhab99** [comment]
Yup that worked
